import fs from 'fs';
import path from 'path';
const ROOT='/tmp/yilbay0111';
const serverPath=path.join(ROOT,'app','server.js'),appPath=path.join(ROOT,'app','public','app.js');
let s=fs.readFileSync(serverPath,'utf8'),a=fs.readFileSync(appPath,'utf8');
s=s.replaceAll('0.11.0','0.11.1');a=a.replaceAll('0.11.0','0.11.1');fs.writeFileSync(path.join(ROOT,'app','VERSION'),'0.11.1\n','utf8');
function between(src,start,end,repl){const i=src.indexOf(start),j=src.indexOf(end,i+start.length);if(i<0||j<0)throw new Error('anchor '+start);return src.slice(0,i)+repl+src.slice(j)}
const helpers=[
"function homeworkMathVerificationInstruction(){return `LUNA YÜKSEK ÇÖZÜNÜRLÜKLÜ MATEMATİK DOĞRULAMA PROTOKOLÜ:\nBu çağrıda yalnız verilen hedef soruları, kendilerine ait yüksek çözünürlüklü SAYFA GÖRÜNTÜLERİ üzerinde yeniden incele. PDF'nin tamamı bu çağrıda yoktur.\nHer hedef için sectionKey, section, page ve printedNumber kimliğini aynen koru. Önce öğrencinin görünür el yazısındaki matematiksel ifadeleri SATIR SATIR transkribe et. +, -, ×, ÷, /, =, <, >, ≤, ≥, parantez, üs, kök, kesir çizgisi ve değişken sembollerini ayrı ayrı doğrula.\nOkunamayan sembolü tahmin etme; transcriptionLines içinde [BELİRSİZ] yaz ve symbolConfidence değerini düşür.\nTranskripsiyon tamamlanmadan matematiksel yorum yapma. Sonra işlemleri satır satır yeniden hesapla ve finalStatus değerini correct|wrong|blank|uncertain olarak ver.\nYanlışsa firstErrorStep ilk gerçekten hatalı matematik adımı olmalı. errorCategory conceptual|arithmetic|attention|method|incomplete|uncertain değerlerinden biri olsun. betterApproach kısa ve matematiksel olarak doğru çözüm yolunu versin.\nSembol güveni 0.80 altındaysa finalStatus=uncertain yap; kesin hüküm verme.\nYalnız geçerli kısa JSON döndür.\n`}",
"function homeworkMathVerificationTargets(x={}){const out=[],seen=new Set();for(const q of [...(Array.isArray(x.wrongQuestions)?x.wrongQuestions:[]),...(Array.isArray(x.uncertainQuestions)?x.uncertainQuestions:[])]){const n=normalizeHomeworkQuestionRef(q);if(n&&!seen.has(n.questionId)){seen.add(n.questionId);out.push(n)}}return out.slice(0,80)}",
"function renderHomeworkTargetPages(studentFile={},targets=[]){const browser=String(process.env.YILBAY_BROWSER_PATH||'').trim(),pages=[...new Set(targets.map(q=>Number(q.page)).filter(n=>Number.isInteger(n)&&n>0))].sort((x,y)=>x-y),result={mode:'high_res_page_png',requestedPages:pages,renderedPages:[],failures:[],images:[]};if(!pages.length)return result;if(!browser||!fs.existsSync(browser)){result.failures.push({page:0,error:'browser_missing'});return result}const dir=path.join(runtime,'math_verify_'+Date.now()+'_'+Math.random().toString(16).slice(2));fs.mkdirSync(dir,{recursive:true});try{const pdf=path.join(dir,'student.pdf');fs.writeFileSync(pdf,Buffer.from(String(studentFile.base64||''),'base64'));const fileUrl='file:///'+pdf.split(path.sep).join('/');for(const pageNo of pages){const out=path.join(dir,'page_'+pageNo+'.png'),profile=path.join(dir,'profile_'+pageNo),url=encodeURI(fileUrl)+'#page='+pageNo+'&zoom=page-width';const args=['--headless=new','--disable-gpu','--hide-scrollbars','--no-first-run','--disable-extensions','--force-device-scale-factor=2','--window-size=1700,2200','--virtual-time-budget=3000','--user-data-dir='+profile,'--screenshot='+out,url];let r;try{r=cp.spawnSync(browser,args,{windowsHide:true,timeout:18000,stdio:'ignore'})}catch(e){result.failures.push({page:pageNo,error:'spawn_'+String(e.message||e).slice(0,120)});continue}try{const b=fs.readFileSync(out),png=b.length>15000&&b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47;if(!png){result.failures.push({page:pageNo,error:'invalid_png'});continue}result.renderedPages.push(pageNo);result.images.push({page:pageNo,bytes:b.length,base64:b.toString('base64')})}catch{result.failures.push({page:pageNo,error:'screenshot_missing_'+String(r?.status??'')})}}}finally{fs.rmSync(dir,{recursive:true,force:true})}return result}",
"function applyHomeworkMathVerification(x={},reviews=[]){const targets=new Set(homeworkMathVerificationTargets(x).map(q=>q.questionId)),verified=new Map();for(const r of Array.isArray(reviews)?reviews:[]){const q=normalizeHomeworkQuestionRef(r);if(!q||!targets.has(q.questionId))continue;const symbolConfidence=Math.max(0,Math.min(1,Number(r.symbolConfidence)||0)),raw=String(r.finalStatus||'uncertain'),finalStatus=symbolConfidence>=0.80&&['correct','wrong','blank'].includes(raw)?raw:'uncertain';verified.set(q.questionId,{...r,...q,finalStatus,symbolConfidence,status:finalStatus==='wrong'?'wrong':finalStatus,question:q.printedNumber,questionLabel:q.label})}const correctQuestions=[...(x.correctQuestions||[])],blankQuestions=[...(x.blankQuestions||[])],uncertainQuestions=[],items=[];for(const q of homeworkMathVerificationTargets(x)){const v=verified.get(q.questionId);if(!v){uncertainQuestions.push(q);continue}if(v.finalStatus==='correct')correctQuestions.push(q);else if(v.finalStatus==='blank')blankQuestions.push(q);else if(v.finalStatus==='wrong')items.push(v);else uncertainQuestions.push(q)}const merged=finalizeHomeworkQuestionSets({...x,correctQuestions,blankQuestions,uncertainQuestions,items,needsTeacherReview:false,autoFinalize:true});const reviewed=verified.size,low=[...verified.values()].filter(v=>v.symbolConfidence<0.80||v.finalStatus==='uncertain').length,targetCount=targets.size,complete=reviewed===targetCount&&low===0,objectiveReview=!complete||merged.questionAccountingVerified===false||Number(merged.questionStatusConflictCount||0)>0||x.pdfCoverageVerified===false||x.answerKeyFound!==true||Number(x.answerKeyConfidence||0)<0.75;return {...merged,mathVerificationTargetCount:targetCount,mathVerificationReviewedCount:reviewed,mathVerificationLowConfidenceCount:low,mathVerificationComplete:complete,mathVerificationUsed:targetCount>0,needsTeacherReview:objectiveReview,autoFinalize:!objectiveReview}}"
].join('\n')+'\n';
s=between(s,'function homeworkMathVerificationInstruction(){','async function handleHomework(req,res){',helpers);
const oldHandleStart=s.indexOf('async function handleHomework(req,res){'),oldHandleEnd=s.indexOf('\nfunction reportText',oldHandleStart);if(oldHandleStart<0||oldHandleEnd<0)throw new Error('handle bounds');
const handle=[
"async function handleHomework(req,res){",
"  const totalStarted=Date.now(),body=await readJson(req,18*1024*1024);",
"  const {assignment,answerKey=null,resourceContext=null,studentFileSource='local'}=body;",
"  let studentFile;try{studentFile=await resolveStudentHomeworkFile(body)}catch(e){return json(res,400,{ok:false,error:e.message})}",
"  if(!integrationStatus().openai.configured)return json(res,400,{ok:false,error:'Ödev analizi için OpenAI API anahtarı gerekli'});",
"  const expectedStudentPages=estimatePdfPageCount(studentFile.base64,studentFile.mimeType);",
"  const safeContext=resourceContext?{resourceId:resourceContext.resourceId||null,course:resourceContext.course||assignment?.course||'',unit:resourceContext.unit||'',topic:resourceContext.topic||assignment?.topic||'',level:resourceContext.level||'',title:resourceContext.title||assignment?.title||''}:null;",
"  const meta={assignment:{id:assignment?.id||null,course:assignment?.course||'',topic:assignment?.topic||'',title:assignment?.title||''},resourceContext:safeContext,manualAnswerKey:answerKey||null};",
"  const firstStarted=Date.now();",
"  const firstContent=[{type:'input_text',text:JSON.stringify(meta)},{type:'input_text',text:'BİRİNCİ GEÇİŞ: Tüm sayfaları tara; bölüm/test ve soru kimliklerini koru. Yalnız doğru/yanlış/boş/belirsiz sınıflaması yap. Yanlış çözüm ayrıntısını bu geçişte üretme.'},{type:'input_file',filename:studentFile.fileName,file_data:'data:'+studentFile.mimeType+';base64,'+studentFile.base64}];",
"  const scanSchema='Sadece geçerli ve KISA JSON döndür. Şema: {\\\"confidence\\\":number,\\\"needsTeacherReview\\\":boolean,\\\"correctQuestions\\\":[{\\\"sectionKey\\\":\\\"string\\\",\\\"section\\\":\\\"string\\\",\\\"page\\\":number,\\\"printedNumber\\\":number}],\\\"blankQuestions\\\":[aynı kimlik],\\\"uncertainQuestions\\\":[aynı kimlik],\\\"items\\\":[{\\\"sectionKey\\\":\\\"string\\\",\\\"section\\\":\\\"string\\\",\\\"page\\\":number,\\\"printedNumber\\\":number,\\\"status\\\":\\\"wrong\\\"}],\\\"reasoningProfile\\\":{\\\"strengths\\\":[],\\\"recurringErrors\\\":[],\\\"conceptualGaps\\\":[],\\\"proceduralGaps\\\":[],\\\"attentionPatterns\\\":[],\\\"recommendedActions\\\":[],\\\"summary\\\":\\\"\\\"},\\\"summary\\\":\\\"string\\\",\\\"answerKeyFound\\\":boolean,\\\"answerKeySource\\\":\\\"manual|embedded_same_page|embedded_adjacent_page|embedded_end_pages|ambiguous|none\\\",\\\"answerKeyOriginDocument\\\":\\\"manual|student_pdf|ambiguous|none\\\",\\\"answerKeyConfidence\\\":number,\\\"answerKeyEvidence\\\":\\\"string\\\",\\\"analyzedStudentPages\\\":[number]}';",
"  const firstAi=await openaiRequest({instructions:lunaHomeworkDirectInstruction()+'\\n'+scanSchema,input:[{role:'user',content:firstContent}],reasoning:'low'});",
"  const firstPassMs=Date.now()-firstStarted;let parsed=normalizeHomeworkAnalysis(parseJsonText(firstAi.text));parsed=finalizeHomeworkQuestionSets(parsed);parsed=validateLunaDirectAnswerKey(parsed,answerKey);parsed=validateHomeworkPageCoverage(parsed,expectedStudentPages,0);parsed=validateLunaQuestionAccounting(parsed);parsed=deriveHomeworkReviewReasons(parsed);",
"  const firstCost=appendUsage('homework_scan',firstAi.model,firstAi.data?.usage||{}, {studentId:assignment?.studentId||null,assignmentId:assignment?.id||null});",
"  const targets=homeworkMathVerificationTargets(parsed);let secondAi=null,secondCost=null,secondPassMs=0,render={mode:'high_res_page_png',requestedPages:[],renderedPages:[],failures:[],images:[]};",
"  if(targets.length){const secondStarted=Date.now();render=renderHomeworkTargetPages(studentFile,targets);const renderPages=new Set(render.renderedPages),activeTargets=targets.filter(q=>renderPages.has(Number(q.page)));if(activeTargets.length&&render.images.length){const targetMeta=activeTargets.map(q=>({sectionKey:q.sectionKey,section:q.section,page:q.page,printedNumber:q.printedNumber,questionId:q.questionId})),secondContent=[{type:'input_text',text:JSON.stringify({targets:targetMeta,manualAnswerKey:answerKey||null})},{type:'input_text',text:'İKİNCİ GEÇİŞ: Yalnız hedef soruları yüksek çözünürlüklü sayfa görüntülerinde incele. Önce sembolleri satır satır transkribe et; sonra matematiği kontrol et.'}];for(const im of render.images){secondContent.push({type:'input_text',text:'Fiziksel PDF sayfası '+im.page+' yüksek çözünürlüklü görüntüsü:'});secondContent.push({type:'input_image',image_url:'data:image/png;base64,'+im.base64,detail:'high'})}const verifySchema='Yalnız JSON: {\\\"reviews\\\":[{\\\"sectionKey\\\":\\\"string\\\",\\\"section\\\":\\\"string\\\",\\\"page\\\":number,\\\"printedNumber\\\":number,\\\"finalStatus\\\":\\\"correct|wrong|blank|uncertain\\\",\\\"transcriptionLines\\\":[\\\"string\\\"],\\\"symbolConfidence\\\":number,\\\"studentAnswer\\\":\\\"string|null\\\",\\\"correctAnswer\\\":\\\"string|null\\\",\\\"approach\\\":\\\"string|null\\\",\\\"stepsSummary\\\":[\\\"string\\\"],\\\"firstErrorStep\\\":\\\"string|null\\\",\\\"errorCategory\\\":\\\"conceptual|arithmetic|attention|method|incomplete|uncertain\\\",\\\"betterApproach\\\":\\\"string|null\\\",\\\"learningObjective\\\":\\\"string|null\\\",\\\"solutionConfidence\\\":number,\\\"note\\\":\\\"string|null\\\"}]}';secondAi=await openaiRequest({instructions:homeworkMathVerificationInstruction()+'\\n'+verifySchema,input:[{role:'user',content:secondContent}],reasoning:'low'});const secondParsed=parseJsonText(secondAi.text);parsed=applyHomeworkMathVerification(parsed,secondParsed.reviews);secondCost=appendUsage('homework_math_verify_image',secondAi.model,secondAi.data?.usage||{}, {studentId:assignment?.studentId||null,assignmentId:assignment?.id||null,targetCount:targets.length,renderedPages:render.renderedPages.length})}else{parsed=applyHomeworkMathVerification(parsed,[])}secondPassMs=Date.now()-secondStarted;parsed=validateLunaQuestionAccounting(parsed);parsed=deriveHomeworkReviewReasons(parsed)}else{parsed={...parsed,mathVerificationTargetCount:0,mathVerificationReviewedCount:0,mathVerificationLowConfidenceCount:0,mathVerificationComplete:true,mathVerificationUsed:false}}",
"  const totalMs=Date.now()-totalStarted,cost={try:Number(firstCost?.try||0)+Number(secondCost?.try||0),usd:Number(firstCost?.usd||0)+Number(secondCost?.usd||0),firstPass:firstCost,secondPass:secondCost};",
"  parsed.studentFileSource=studentFileSource;parsed.studentFileDriveUsed=!!studentFile.driveUsed;parsed.analysisArchitecture='two_pass_luna_high_res_page_png';parsed.mathVerificationRenderMode=render.mode;parsed.mathVerificationRequestedPages=render.requestedPages;parsed.mathVerificationRenderedPages=render.renderedPages;parsed.mathVerificationRenderFailureCount=render.failures.length;parsed.firstPassMs=firstPassMs;parsed.secondPassMs=secondPassMs;parsed.totalAnalysisMs=totalMs;parsed.firstPassCostTry=Number(firstCost?.try||0);parsed.secondPassCostTry=Number(secondCost?.try||0);",
"  writeHomeworkDiagnostic(parsed,cost,assignment);return json(res,200,{ok:true,analysis:parsed,autoFinalize:parsed.autoFinalize,usage:{firstPass:firstAi.data?.usage||null,secondPass:secondAi?.data?.usage||null},cost});",
"}",
""
].join('\n');
s=s.slice(0,oldHandleStart)+handle+s.slice(oldHandleEnd);
const dStart=s.indexOf('function writeHomeworkDiagnostic(analysis={},cost=null,assignment=null){'),dEnd=s.indexOf('\nfunction validateHomeworkQuestionAccounting',dStart);if(dStart<0||dEnd<0)throw new Error('diag bounds');let diag=s.slice(dStart,dEnd);diag=diag.replace("mathVerificationComplete:analysis.mathVerificationComplete===true,","mathVerificationComplete:analysis.mathVerificationComplete===true,mathVerificationRenderMode:String(analysis.mathVerificationRenderMode||''),mathVerificationRequestedPages:Array.isArray(analysis.mathVerificationRequestedPages)?analysis.mathVerificationRequestedPages.slice(0,100):[],mathVerificationRenderedPages:Array.isArray(analysis.mathVerificationRenderedPages)?analysis.mathVerificationRenderedPages.slice(0,100):[],mathVerificationRenderFailureCount:Number(analysis.mathVerificationRenderFailureCount)||0,");s=s.slice(0,dStart)+diag+s.slice(dEnd);
const as=s.indexOf('function assignments(){'),ae=s.indexOf('\nwindow.scannedPdfHistory=',as);if(as<0||ae<0)throw new Error('assignment anchors');const assign=[
"function assignments(){",
" const rows=db.assignments.slice().reverse().map(a=>`<tr><td><div class=\"cell-title\">${studentName(a.studentId)}</div></td><td><span class=\"badge info\">${a.kind}</span></td><td><div class=\"cell-title\">${a.title}</div><div class=\"cell-sub\">${a.course} · ${a.topic}</div></td><td><span class=\"badge ${a.status===\"Tamamlandı\"?\"good\":\"mid\"}\">${a.status}</span></td><td><div class=\"row-actions\">${a.status===\"Tamamlandı\"?'<span class=\"muted\">Tamamlandı</span>':a.status===\"Öğretmen Kontrolü\"?`<button class=\"btn primary small\" onclick=\"reviewHomeworkAnalysis(${a.id})\">AI analizini kontrol et</button><button class=\"btn ghost small\" onclick=\"analyzeAssignment(${a.id})\">Yeniden tara</button>`:`<button class=\"btn ghost small\" onclick=\"completeAssignment(${a.id})\">Manuel sonuç</button>${a.kind===\"PDF Kaynak\"?`<button class=\"btn primary small\" onclick=\"analyzeAssignment(${a.id})\">AI ile ödevi tara</button>`:''}`}<button class=\"btn danger small\" onclick=\"deleteAssignment(${a.id})\">Sil</button></div></td></tr>`).join('');",
" const actions='<button class=\"btn ghost\" onclick=\"scannedPdfHistory()\">Taranmış PDFler</button> '+(db.assignments.length?'<button class=\"btn danger\" onclick=\"clearAssignments()\">Atama Listesini Temizle</button> ':'')+'<button class=\"btn primary\" onclick=\"assignmentModal()\">+ Yeni Atama</button>';",
" shell(`${pageHead('Atamalar','Öğrencilere kaynak ve online sınav atayın, tamamlanma durumunu takip edin.',actions)}${rows?tableWrap(`<table><thead><tr><th>Öğrenci</th><th>Tür</th><th>İçerik</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>${rows}</tbody></table>`):emptyState('Henüz atama yok','Yeni atama oluşturarak çalışma akışını başlatın.')}`,'assignments')",
"}",
"window.deleteAssignment=id=>{const x=db.assignments.find(a=>Number(a.id)===Number(id));if(!x||!confirm('Bu atama listeden silinsin mi? Akademik sonuçlar ve AI analiz geçmişi korunur.'))return;db.assignments=db.assignments.filter(a=>Number(a.id)!==Number(id));save();assignments()}",
"window.clearAssignments=()=>{if(!db.assignments.length||!confirm('Atamalar ekranındaki TÜM kayıtlar silinsin mi? Akademik sonuçlar ve AI analiz geçmişi korunur.'))return;db.assignments=[];save();assignments()}",
""
].join('\n');a=a.slice(0,as)+assign+a.slice(ae);
fs.writeFileSync(serverPath,s,'utf8');fs.writeFileSync(appPath,a,'utf8');console.log('v0.11.1 high-res page math + assignment cleanup patch applied');
