import fs from 'fs';
import path from 'path';
const p='/tmp/yilbay0110/app/public/app.js';let a=fs.readFileSync(p,'utf8');
const start=a.indexOf('function processedHomeworkPdfRows(){'),end=a.indexOf('window.assignmentModal=',start);if(start<0||end<0)throw new Error('frontfix anchors');
const block=`function assignments(){
 const rows=db.assignments.slice().reverse().map(a=>\`<tr><td><div class="cell-title">\${studentName(a.studentId)}</div></td><td><span class="badge info">\${a.kind}</span></td><td><div class="cell-title">\${a.title}</div><div class="cell-sub">\${a.course} · \${a.topic}</div></td><td><span class="badge \${a.status==="Tamamlandı"?"good":"mid"}">\${a.status}</span></td><td>\${a.status==="Tamamlandı"?\`<span class="muted">Tamamlandı</span>\`:a.status==="Öğretmen Kontrolü"?\`<div class="row-actions"><button class="btn primary small" onclick="reviewHomeworkAnalysis(\${a.id})">AI analizini kontrol et</button><button class="btn ghost small" onclick="analyzeAssignment(\${a.id})">Yeniden tara</button></div>\`:\`<div class="row-actions"><button class="btn ghost small" onclick="completeAssignment(\${a.id})">Manuel sonuç</button>\${a.kind==="PDF Kaynak"?\`<button class="btn primary small" onclick="analyzeAssignment(\${a.id})">AI ile ödevi tara</button>\`:""}</div>\`}</td></tr>\`).join("");
 const actions='<button class="btn ghost" onclick="scannedPdfHistory()">Taranmış PDFler</button> <button class="btn primary" onclick="assignmentModal()">+ Yeni Atama</button>';
 shell(\`\${pageHead("Atamalar","Öğrencilere kaynak ve online sınav atayın, tamamlanma durumunu takip edin.",actions)}\${rows?tableWrap(\`<table><thead><tr><th>Öğrenci</th><th>Tür</th><th>İçerik</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>\${rows}</tbody></table>\`):emptyState("Henüz atama yok","Yeni atama oluşturarak çalışma akışını başlatın.")}\`,"assignments")
}
window.scannedPdfHistory=()=>{const xs=db.homeworkAnalyses.slice().reverse(),rows=xs.map(function(x){return '<tr><td>'+studentName(x.studentId)+'</td><td>'+(x.fileName||'Ödev PDF')+'</td><td>'+(x.date||'—')+'</td><td>'+(x.totalQuestions||0)+'</td><td><button class="btn danger small" onclick="deleteScannedPdfRecord('+Number(x.id)+')">Sil</button></td></tr>'}).join(''),clear=xs.length?'<button class="btn danger" onclick="clearScannedPdfRecords()">Tüm taranmış PDF kayıtlarını sil</button>':'';modal('<h2>İşlenen / Taranmış PDFler</h2><p class="muted">Yerel ödev dosyasının kendisi kalıcı tutulmaz. Bu liste analiz kaydını ve varsa yerel karne PDF dosyasını yönetir. Drive üzerindeki asıl dosya silinmez.</p>'+(rows?tableWrap('<table><thead><tr><th>Öğrenci</th><th>PDF</th><th>Tarih</th><th>Soru</th><th>İşlem</th></tr></thead><tbody>'+rows+'</tbody></table>'):emptyState('Taranmış PDF yok','AI ile analiz edilen ödevler burada listelenecek.'))+'<div class="modal-actions">'+clear+' <button class="btn ghost" onclick="closeModal()">Kapat</button></div>')}
window.deleteScannedPdfRecord=async id=>{const x=db.homeworkAnalyses.find(v=>Number(v.id)===Number(id));if(!x||!confirm('Bu taranmış PDF analiz kaydı silinsin mi? Drive veya bilgisayardaki asıl dosya etkilenmez.'))return;if(x.pdfReportUrl){try{await fetch(x.pdfReportUrl,{method:'DELETE'})}catch{}}db.homeworkAnalyses=db.homeworkAnalyses.filter(v=>Number(v.id)!==Number(id));save();scannedPdfHistory()}
window.clearScannedPdfRecords=async()=>{if(!db.homeworkAnalyses.length||!confirm('Tüm taranmış PDF analiz kayıtları ve yerel karne PDF dosyaları silinsin mi? Asıl dosyalar etkilenmez.'))return;for(const x of db.homeworkAnalyses){if(x.pdfReportUrl){try{await fetch(x.pdfReportUrl,{method:'DELETE'})}catch{}}}db.homeworkAnalyses=[];save();scannedPdfHistory()}
`;
a=a.slice(0,start)+block+a.slice(end);fs.writeFileSync(p,a,'utf8');console.log('v0.11.0 frontend fixed');
