import fs from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';
import { parse } from '/tmp/microtools/node_modules/acorn/dist/acorn.mjs';
await import(pathToFileURL(path.resolve('release_build/v0.11.0/frontfix_v0110.mjs')).href);
await import(pathToFileURL(path.resolve('release_build/v0.11.0/backfix_v0110.mjs')).href);
await import(pathToFileURL(path.resolve('release_build/v0.11.0/compat_v0110.mjs')).href);
const ROOT='/tmp/yilbay0110';
const cellsRoot=path.join(ROOT,'cells','micro');
function slug(s){return String(s||'statement').replace(/[^A-Za-z0-9_$-]+/g,'-').replace(/^-+|-+$/g,'').toLowerCase()||'statement'}
function nodeName(node,idx,side){if(node.type==='FunctionDeclaration')return node.id?.name||`function-${idx}`;if(node.type==='VariableDeclaration'){const names=node.declarations.map(d=>d.id?.name).filter(Boolean);return names.length===1?names[0]:`core-vars-${idx}`}if(node.type==='ExpressionStatement'){const e=node.expression;if(e?.type==='AssignmentExpression'){const l=e.left;if(l?.type==='MemberExpression'&&l.object?.name==='window')return l.computed?(l.property?.value||`window-action-${idx}`):(l.property?.name||`window-action-${idx}`);if(l?.type==='Identifier')return l.name}if(e?.type==='CallExpression'){const c=e.callee;if(c?.type==='MemberExpression'&&c.object?.type==='CallExpression')return `server-listen-${idx}`;if(c?.type==='MemberExpression')return `${c.object?.name||'call'}-${c.property?.name||idx}`}}return `${side}-statement-${idx}`}
function splitFile(rel,side){const full=path.join(ROOT,rel),src=fs.readFileSync(full,'utf8');let ast;try{ast=parse(src,{ecmaVersion:'latest',sourceType:'script',allowHashBang:true})}catch(e){const lines=src.split(/\r?\n/),line=e.loc?.line||1;console.error('PARSE_SIDE',side,'LINE',line,'COL',e.loc?.column);for(let i=Math.max(0,line-5);i<Math.min(lines.length,line+4);i++)console.error(String(i+1).padStart(4,'0')+': '+lines[i]);throw e}const dir=path.join(cellsRoot,side);fs.rmSync(dir,{recursive:true,force:true});fs.mkdirSync(dir,{recursive:true});const files=[];let prev=0;ast.body.forEach((node,i)=>{const nextStart=i+1<ast.body.length?ast.body[i+1].start:src.length;const seg=src.slice(prev,nextStart);if(!seg.trim())return;const fn=`${String(i+1).padStart(3,'0')}-${slug(nodeName(node,i+1,side))}.cell.js`;const relp=path.posix.join('cells','micro',side,fn);fs.writeFileSync(path.join(ROOT,relp),seg,'utf8');files.push({file:relp,nodeType:node.type,name:nodeName(node,i+1,side),start:node.start,end:node.end});prev=nextStart});const rebuilt=files.map(x=>fs.readFileSync(path.join(ROOT,x.file),'utf8')).join('');if(rebuilt!==src)throw new Error(`${side}: exact bundle reconstruction failed`);return files}
const frontend=splitFile('app/public/app.js','frontend'),backend=splitFile('app/server.js','backend');const manifest={protocol:'micro-cell-v2-ast',version:'0.11.0',rule:'one-Program.body-node-per-cell',frontend,backend,counts:{frontend:frontend.length,backend:backend.length,totalJs:frontend.length+backend.length},designSystem:['cells/design-system/00-design-system.cell.css'],runtimeBundlesAreGenerated:true,parser:'acorn-ecma-latest'};fs.writeFileSync(path.join(ROOT,'cells','micro-cell-manifest.json'),JSON.stringify(manifest,null,2),'utf8');console.log(JSON.stringify(manifest.counts));
