'use strict';
const API='/api/ana-prg',app=document.querySelector('#app'),dialog=document.querySelector('#dialog');
const S={session:null,page:'',catalog:{courses:{},formats:{}},meta:{},items:[],offset:0,search:'',studentTab:'program'};
const nav=[['','Genel Bakış','◫'],['program','Haftalık Program','▦'],['classes','Sınıflar & Öğrenciler','♧'],['homework','Ödev Havuzu','▤'],['assignments','Atamalar','↗'],['submissions','Teslimler','↧'],['ai','AI Değerlendirme','✦'],['whatsapp','WhatsApp','◎'],['mock-exams','Deneme Kulübü','♜'],['reports','Raporlar','▥'],['settings','Ayarlar','⚙'],['system','Sistem Yönetimi','⌘']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const courses=()=>Object.entries(S.catalog.courses);
const name=(kind,id)=>S.meta[kind]?.find(x=>x.id===id)?.name||id||'—';
const course=c=>S.catalog.courses[c]||c||'—';
const badge=status=>`<span class="badge ${['APPROVED','READY','DONE','SENT'].includes(status)?'good':['FAILED','UNCERTAIN'].includes(status)?'bad':'warn'}">${esc(({ASSIGNED:'Atandı',SUBMITTED:'Teslim edildi',APPROVED:'Onaylı',REVIEW:'Kontrol bekliyor',QUEUED:'Kuyrukta',RUNNING:'İşleniyor',DONE:'Tamamlandı',FAILED:'Başarısız',UNCERTAIN:'Belirsiz',READY:'Hazır',KEY_MISSING:'Anahtar eksik',KEY_REVIEW:'Anahtar kontrolü',SENT:'Gönderildi',ARCHIVED:'Arşiv'}[status])||status||'—')}</span>`;
const linkFile=id=>id?`<a href="${API}/files/${encodeURIComponent(id)}/content" target="_blank" rel="noopener">Dosyayı aç ↗</a>`:'—';
const btn=(action,label,extra='',cls='')=>`<button type="button" data-action="${action}" ${extra} class="${cls}">${label}</button>`;
const empty=(title='Henüz kayıt yok',text='Yeni kayıt ekleyerek başlayın.')=>`<div class="empty"><strong>${esc(title)}</strong>${esc(text)}</div>`;
const table=(headers,rows)=>rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty();
const card=(label,n,note='')=>`<div class="card"><div class="label">${esc(label)}</div><div class="number">${esc(n)}</div><div class="small muted">${esc(note)}</div></div>`;
let noticeTimer;
function notice(text,error=false){const e=document.querySelector('#notice');e.textContent=text;e.className=error?'error':'';e.style.display='block';clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>e.style.display='none',8000)}
async function api(path,method='GET',body=null){const options={method,credentials:'same-origin',headers:{}};if(method!=='GET')options.headers['X-ANA-CSRF']=S.session?.csrf||'';if(body instanceof FormData)options.body=body;else if(body!==null){options.headers['Content-Type']='application/json';options.body=JSON.stringify(body)}const r=await fetch(API+path,options);const out=await r.json().catch(()=>({detail:'Sunucudan geçersiz yanıt geldi.'}));if(!r.ok)throw new Error(out.detail||'İşlem tamamlanamadı.');return out}
async function busy(button,work){const before=button?.textContent;if(button){button.disabled=true;button.textContent='İşleniyor…'}try{return await work()}catch(e){notice(e.message,true);throw e}finally{if(button?.isConnected){button.disabled=false;button.textContent=before}}}
function modal(title,body,footer=''){document.querySelector('#dialog-content').innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2>${btn('close','×','aria-label="Kapat"','quiet')}</div>${body}${footer}`;if(!dialog.open)dialog.showModal()}
function close(){dialog.close();document.querySelector('#dialog-content').replaceChildren()}
function dateMonday(){const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7));return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function heading(title,note,actions=''){return `<div class="page-head"><div><h1>${esc(title)}</h1><div class="muted">${esc(note)}</div></div><div class="actions">${actions}</div></div>`}
function shell(){const current=nav.find(n=>n[0]===S.page)||nav[0];app.innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="/ana-prg">ANA PRG<small>GENESIS · EĞİTİM YÖNETİMİ</small></a><nav>${nav.map(([path,label,icon])=>`<a href="/ana-prg${path?'/'+path:''}" data-nav="${path}" class="${path===S.page?'active':''}"><span>${icon}</span>${label}</a>`).join('')}</nav><div class="bottom"><a href="/">← GENESIS ana ekran</a><p class="muted small" style="margin-top:15px">Öğrenci portalı<br><a href="/ana-prg/student" target="_blank">Portalı aç ↗</a></p></div></aside><div class="main"><header class="top"><div class="left">${btn('menu','☰','aria-label="Menüyü aç"','mobile-menu quiet')}<span>${esc(current[1])}</span><span class="dot"></span></div><div class="actions"><span>Öğretmen</span>${btn('refresh','Yenile','','quiet')}${btn('logout','Çıkış','','quiet')}</div></header><main class="content" id="content"><div class="loading">Yükleniyor…</div></main></div></div>`}
function login(student){app.innerHTML=`<div class="login"><section class="login-card"><a class="brand" href="/">GENESIS<small>ANA PRG · EĞİTİM YÖNETİMİ</small></a><h1>${student?'Öğrenci portalı':'Öğretmen girişi'}</h1><p class="muted">${student?'Programınız, ödevleriniz ve deneme sonuçlarınız tek yerde.':'GENESIS yönetici hesabınızla ANA PRG’ye giriş yapın.'}</p><form id="login-form" data-student="${student}"><label for="login-code">${student?'Öğrenci kodu':'Kullanıcı adı'}</label><input id="login-code" name="code" autocomplete="username" required maxlength="80"><label for="login-password">${student?'PIN':'Şifre'}</label><input id="login-password" name="password" type="password" autocomplete="current-password" required maxlength="200"><div class="actions"><button class="primary" type="submit">Giriş yap →</button></div><div class="form-error" id="login-error" role="alert"></div></form><div class="links"><a href="${student?'/ana-prg':'/ana-prg/student'}">${student?'Öğretmen girişi':'Öğrenci portalı'}</a><a href="/">GENESIS</a></div></section></div>`}
async function metadata(){const endpoints={classes:'classes',students:'students',homework:'homework',files:'files',exams:'mock-exams',templates:'templates',rules:'course-rules',guardians:'guardians'};const all=await Promise.all(Object.entries(endpoints).map(async([key,path])=>[key,(await api('/'+path+'?limit=500')).items]));S.meta=Object.fromEntries(all)}
async function boot(){S.page=location.pathname.replace(/^\/ana-prg\/?/,'').split('/')[0];try{const me=await api('/auth/me');if(!me.authenticated){login(S.page==='student');return}S.session=me;S.catalog=await api('/catalog');if(me.role==='STUDENT'){if(S.page!=='student')history.replaceState({},'', '/ana-prg/student');S.page='student';await studentPage();return}if(S.page==='student'){login(true);return}await metadata();shell();await render()}catch(e){app.innerHTML=`<div class="content error">${esc(e.message)} ${btn('reload','Tekrar dene')}</div>`}}
async function navigate(path){S.page=path;S.offset=0;S.search='';history.pushState({},'', '/ana-prg'+(path?'/'+path:''));shell();await render()}
async function render(){const content=document.querySelector('#content');if(!content)return;content.innerHTML='<div class="loading">Yükleniyor…</div>';try{if(S.page==='')await dashboard(content);else if(S.page==='classes')await classesPage(content);else if(S.page==='program')await programPage(content);else if(S.page==='ai')await aiPage(content);else if(S.page==='whatsapp')await whatsappPage(content);else if(S.page==='mock-exams')await examsPage(content);else if(S.page==='reports')await reportsPage(content);else if(S.page==='settings')await settingsPage(content);else if(S.page==='system')await systemPage(content);else await listPage(content,S.page)}catch(e){content.innerHTML=`<div class="error">${esc(e.message)} ${btn('refresh','Tekrar dene')}</div>`}}
function bars(data){const entries=Object.entries(data),max=Math.max(1,...entries.map(e=>e[1]));return entries.length?`<div class="bars">${entries.map(([key,n])=>`<div class="bar-row"><span>${esc(course(key))}</span><div class="bar-track"><i style="width:${n/max*100}%"></i></div><span>${esc(n)}</span></div>`).join('')}</div>`:empty('Ders dağılımı oluşmadı','Ödev atamalarından sonra burada görünecek.')}
function spark(rows){if(!rows.length)return empty('Henüz deneme sonucu yok');const values=rows.map(r=>r.report.totals.net),min=Math.min(0,...values),max=Math.max(1,...values),points=values.map((v,i)=>`${20+i*(560/Math.max(1,values.length-1))},${105-(v-min)/(max-min)*85}`).join(' ');return `<svg class="spark" viewBox="0 0 600 120" role="img" aria-label="Deneme net trendi"><line x1="20" y1="105" x2="580" y2="105" stroke="#334b6c"/><polyline points="${points}" fill="none" stroke="#61d8b1" stroke-width="3"/>${values.map((v,i)=>`<circle cx="${20+i*(560/Math.max(1,values.length-1))}" cy="${105-(v-min)/(max-min)*85}" r="4" fill="#61d8b1"/>`).join('')}</svg><p class="small muted">${esc(values.join(' → '))} net</p>`}
async function dashboard(c){const d=await api('/dashboard');c.innerHTML=heading('Eğitim yönetimine genel bakış','Programlar, teslimler ve değerlendirmeler için ortak çalışma alanınız.',btn('new','Öğrenci ekle','data-kind="students"','primary')+btn('nav','Haftayı planla','data-page="program"'))+(d.shadow_mode?'<div class="alert">Gölge modu açık. AI ve WhatsApp dış servis çağrıları kapalı; ayarlardan canlı moda geçebilirsiniz.</div>':'')+`<div class="cards">${card('Aktif öğrenci',d.counts.students)}${card('Ödev havuzu',d.counts.homework_pool)}${card('Atama',d.counts.assignments)}${card('Teslim',d.counts.submissions)}${card('AI bekleyen',d.pending_ai)}${card('Deneme sonucu',d.counts.mock_results)}</div><div class="grid"><section class="panel"><h2>Ders dağılımı</h2><div style="margin-top:25px">${bars(d.course_distribution)}</div></section><section class="panel"><h2>Öğrenci tamamlama</h2><div style="margin-top:20px">${table(['Öğrenci','Atama','Teslim','Tamamlama'],Object.entries(d.completion).map(([id,v])=>[esc(name('students',id)),v.total,v.submitted,`${Math.round(100*v.submitted/v.total)}%`]))}</div></section></div><section class="panel"><h2>Son işlemler</h2><div style="margin-top:20px">${table(['Zaman','İşlem','Kullanıcı'],d.recent.map(r=>[esc(r.created_at),esc(r.event),esc(r.actor)]))}</div></section>`}
const defs={
 classes:{title:'Sınıf',path:'classes',fields:[['name','Sınıf adı','text',true],['note','Not','textarea']]},
 students:{title:'Öğrenci',path:'students',fields:[['name','Ad soyad','text',true],['code','Giriş kodu','text',true],['pin','PIN (düzenlerken boş bırakabilirsiniz)','password'],['class_id','Sınıf','classes'],['courses','Koçluk yapılacak dersler','courses',true],['phone','Telefon (E.164, örn. +90…)','tel'],['opt_in','WhatsApp iletişim izni alındı','checkbox'],['note','Not','textarea']]},
 homework:{title:'Ödev',path:'homework',fields:[['name','Ödev / test adı','text',true],['course','Ders','course',true],['source','Kaynak / kitap','text',true],['topic','Konu','text'],['order','Kaynak içindeki PDF sırası','number',true],['test_no','Test numarası','number'],['questions','Soru sayısı','number',true],['file_id','PDF dosyası','files'],['video_url','Çözüm videosu (HTTPS)','url']]},
 assignments:{title:'Atama',path:'assignments',fields:[['student_id','Öğrenci','students',true],['homework_id','Ödev','homework',true],['date','Çalışma tarihi','date',true],['due_at','Son teslim (+03:00)','text'],['note','Not','textarea']]},
 'course-rules':{title:'Ders kuralı',path:'course-rules',fields:[['course','Ders','course',true],['days','Ödev konulacak günler','days',true],['order','Program satır sırası','number',true]]},
 guardians:{title:'Veli',path:'guardians',fields:[['name','Veli adı','text',true],['student_id','Öğrenci','students',true],['phone','Telefon (E.164)','tel',true],['opt_in','WhatsApp iletişim izni alındı','checkbox']]},
 templates:{title:'WhatsApp şablonu',path:'templates',fields:[['name','Görünen ad','text',true],['provider_name','Meta’da onaylı şablon adı','text',true],['language','Dil kodu (tr)','text',true],['body','Önizleme metni','textarea']]},
 'mock-exams':{title:'Deneme sınavı',path:'mock-exams',fields:[['name','Sınav adı','text',true],['kind','Sınav türü','format',true],['date','Sınav tarihi','date',true],['note','Not','textarea']]},
 videos:{title:'Video',path:'videos',fields:[['name','Video adı','text',true],['course','Ders','course',true],['url','Video bağlantısı (HTTPS)','url',true],['topic','Konu','text']]},
 'topic-order':{title:'Konu sırası',path:'topic-order',fields:[['course','Ders','course',true],['topic','Konu','text',true],['order','Sıra','number',true]]},
 'ai-references':{title:'AI referansı',path:'ai-references',fields:[['name','Referans adı','text',true],['homework_id','Ödev','homework'],['file_id','Referans PDF/görsel','files',true],['note','Not','textarea']]}
};
function options(type,value){const opts=type==='course'?courses():type==='format'?Object.entries(S.catalog.formats).map(([k,v])=>[k,v.label]):(S.meta[type]||[]).map(x=>[x.id,x.name]);return `<option value="">Seçin</option>`+opts.map(([id,label])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(label)}</option>`).join('')}
function rawField([key,label,type,required],value){let input;if(type==='courses'||type==='days'){const opts=type==='courses'?courses():['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'].map((d,i)=>[i,d]);input=`<div class="checks">${opts.map(([id,l])=>`<label><input type="checkbox" name="${key}" value="${id}" ${(value||[]).includes(id)?'checked':''}>${esc(l)}</label>`).join('')}</div>`}else if(type==='checkbox')input=`<label><input type="checkbox" name="${key}" ${value?'checked':''}> Evet</label>`;else if(['course','format','classes','students','homework','files','exams','templates'].includes(type))input=`<select name="${key}" ${required?'required':''}>${options(type,value)}</select>`;else if(type==='textarea')input=`<textarea name="${key}" maxlength="4000">${esc(value||'')}</textarea>`;else input=`<input type="${type}" name="${key}" value="${esc(type==='password'?'':value??'')}" ${required?'required':''} ${type==='number'?'min="0" step="1"':'maxlength="200"'}>`;return `<div class="field ${['textarea','courses','days'].includes(type)?'wide':''}"><label>${esc(label)}${required?' *':''}</label>${input}</div>`}
function editor(kind,item={}){const def=defs[kind];if(!def)return;modal(`${item.id?'Düzenle':'Yeni'} · ${def.title}`,`<form id="editor-form" data-kind="${kind}" data-id="${esc(item.id||'')}"><div class="form-grid">${def.fields.map(f=>field(f,item[f[0]])).join('')}</div><div class="form-error" role="alert"></div><div class="dialog-footer">${btn('close','Vazgeç','','quiet')}<button class="primary" type="submit">Kaydet</button></div></form>`)}
async function classesPage(c){const [classes,students]=await Promise.all([api('/classes?limit=500'),api('/students?limit=500')]);S.items=students.items;c.innerHTML=heading('Sınıflar & Öğrenciler','Sınıfları, öğrenci erişimini ve kişisel koçluk derslerini yönetin.',btn('new','Sınıf ekle','data-kind="classes"')+btn('new','Öğrenci ekle','data-kind="students"','primary'))+`<section class="panel"><div class="panel-head"><h2>Sınıflar</h2><span class="muted small">${classes.total} sınıf</span></div>${table(['Sınıf','Öğrenci','Not','İşlem'],classes.items.map(x=>[esc(x.name),students.items.filter(s=>s.class_id===x.id).length,esc(x.note||'—'),rowActions('classes',x)]))}</section><section class="panel"><div class="panel-head"><h2>Öğrenciler</h2><span class="muted small">${students.total} öğrenci</span></div>${table(['Öğrenci','Kod','Sınıf','Koçluk dersleri','WhatsApp','İşlem'],students.items.map(x=>[esc(x.name),esc(x.code),esc(name('classes',x.class_id)),esc((x.courses||[]).map(course).join(', ')),x.opt_in?'<span class="badge good">İzinli</span>':'İzin yok',rowActions('students',x)]))}</section><section class="panel"><div class="panel-head"><h2>Veliler</h2>${btn('new','Veli ekle','data-kind="guardians"')}</div>${table(['Veli','Öğrenci','Telefon','Onay','İşlem'],(S.meta.guardians||[]).map(x=>[esc(x.name),esc(name('students',x.student_id)),esc(x.phone),x.opt_in?'İzinli':'İzin yok',rowActions('guardians',x)]))}</section>`}
function rowActions(kind,item){return btn('edit','Düzenle',`data-kind="${kind}" data-id="${esc(item.id)}"`)+btn('archive','Arşivle',`data-kind="${kind}" data-id="${esc(item.id)}"`,'quiet')}
const listHeaders={homework:['Ödev / kaynak','Ders / konu','Sıra / test','Soru','Dosya','İşlem'],assignments:['Öğrenci','Ödev','Tarih / son teslim','Durum','İşlem'],submissions:['Öğrenci','Ödev','Teslim zamanı','Durum','Dosya','AI']};
async function listPage(c,path){if(!listHeaders[path]){await navigate('');return}const page=await api(`/${path}?limit=100&offset=${S.offset}&search=${encodeURIComponent(S.search)}`);S.items=page.items;const titles={homework:['Ödev Havuzu','PDF kaynaklarını ders, konu ve kaynak sırasıyla yönetin.'],assignments:['Atamalar','Öğrenci bazında çalışma tarihi ve teslim takibi.'],submissions:['Teslimler','Öğrencilerin yüklediği çalışmalar ve değerlendirme durumları.']};let actions=path==='submissions'?'':btn('new',path==='homework'?'Ödev ekle':'Atama ekle',`data-kind="${path}"`,'primary');if(path==='homework')actions=btn('upload','Dosya yükle','data-category="homework"')+actions;let rows=page.items.map(x=>path==='homework'?[`<strong>${esc(x.name)}</strong><div class="meta">${esc(x.source)}</div>`,`${esc(course(x.course))}<div class="meta">${esc(x.topic)}</div>`,`${x.order} / ${x.test_no}`,x.questions,linkFile(x.file_id),rowActions('homework',x)+btn('homework-key','Anahtar',`data-id="${esc(x.id)}"`)]:path==='assignments'?[esc(name('students',x.student_id)),esc(name('homework',x.homework_id)),`${esc(x.date)}<div class="meta">${esc(x.due_at)}</div>`,badge(x.status),rowActions('assignments',x)]:[esc(name('students',x.student_id)),esc(name('homework',x.homework_id)),`${esc(x.submitted_at)}${x.late?'<div class="meta">Geç teslim</div>':''}`,badge(x.status),linkFile(x.file_id),btn('submission-ai','Değerlendir',`data-id="${esc(x.id)}"`)]);c.innerHTML=heading(...titles[path],actions)+`<form id="search-form" class="toolbar"><input name="search" placeholder="Kayıtlarda ara" value="${esc(S.search)}" aria-label="Kayıtlarda ara"><button type="submit">Ara</button><span class="muted">${page.total} kayıt</span></form>`+table(listHeaders[path],rows)+`<div class="pagination">${btn('page-prev','←','',S.offset?'':'quiet')}<span>${S.offset+1}–${Math.min(S.offset+100,page.total)} / ${page.total}</span>${btn('page-next','→',`data-total="${page.total}"`)}</div>`;if(path==='homework')c.innerHTML+=`<div class="grid" style="margin-top:22px"><section class="panel"><div class="panel-head"><h2>Çözüm videoları</h2>${btn('new','Video ekle','data-kind="videos"')}</div>${btn('extra-list','Videoları yönet','data-kind="videos"')}</section><section class="panel"><div class="panel-head"><h2>Konu ve referans sırası</h2>${btn('new','Konu ekle','data-kind="topic-order"')}</div><div class="actions">${btn('extra-list','Konu sıraları','data-kind="topic-order"')}${btn('new','AI referansı','data-kind="ai-references"')}${btn('extra-list','Referanslar','data-kind="ai-references"')}</div></section></div>`}
async function programPage(c){S.week=S.week||dateMonday();const [slots,rules]=await Promise.all([api('/program-slots?limit=500&week='+S.week),api('/course-rules?limit=500')]);S.programSlots=slots.items;S.rules=rules.items;const h=id=>S.meta.homework.find(h=>h.id===id);const days=['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'];c.innerHTML=heading('Haftalık Program','Ders kurallarıyla ortak haftayı oluşturun; seçili dersler öğrencilere atanır.',btn('new','Ders kuralı','data-kind="course-rules"')+btn('program-preview','Önizle')+btn('program-generate','Haftayı oluştur','','primary'))+`<div class="toolbar"><label>Hafta başlangıcı <input type="date" id="week-input" value="${S.week}"></label>${btn('program-sync','Öğrencilere senkronla')}${btn('program-next','Sonraki haftayı oluştur')}${btn('program-reset','Otomatik hücreleri sıfırla','','danger')}</div><div class="table-wrap"><table class="week-grid"><thead><tr><th>Ders</th>${days.map((d,i)=>`<th>${d}</th>`).join('')}</tr></thead><tbody>${rules.items.map(r=>`<tr><td>${esc(course(r.course))}</td>${days.map((d,i)=>{const slot=slots.items.find(x=>x.course===r.course&&x.day===i);return `<td>${slot?`<button class="slot" data-action="program-slot" data-course="${r.course}" data-day="${i}">${esc(h(slot.homework_id)?.name||slot.homework_id)}<div class="meta">${slot.auto?'Otomatik':'Öğretmen'}</div></button>`:btn('program-slot','＋',`data-course="${r.course}" data-day="${i}"`,'quiet')}</td>`}).join('')}</tr>`).join('')}</tbody></table>${!rules.items.length?empty('Ders kurallarını ekleyin','Her ders için günleri seçin; daha sonra ödev havuzundan haftayı üretin.'):''}</div><section class="panel" style="margin-top:22px"><div class="panel-head"><h2>Ders kuralları</h2><span class="small muted">PDF sırası kaynak + sıra + test numarasıyla korunur.</span></div>${table(['Ders','Günler','Sıra','İşlem'],rules.items.map(r=>[esc(course(r.course)),esc((r.days||[]).map(d=>days[d]).join(', ')),r.order,rowActions('course-rules',r)]))}</section>`}
async function aiPage(c){const [queue,evaluations,keys]=await Promise.all([api('/ai/queue?limit=100'),api('/evaluations?limit=100'),api('/answer-keys?limit=100')]);S.aiQueue=queue.items;S.evaluations=evaluations.items;S.keys=keys.items;c.innerHTML=heading('AI Değerlendirme','Luna belgeleri okur; cevap karşılaştırması ve net hesabı kodla yapılır.',btn('queue-ai','AI işi ekle')+btn('run-ai','Kuyruğu çalıştır','','primary'))+`<div class="alert">Düşük güvenli sonuçlar öğretmen onayına gelir. Eksik okuma final sonuç olarak kaydedilmez. Belirsiz servis çağrıları kendiliğinden tekrarlanmaz.</div><section class="panel"><h2>İş kuyruğu</h2><div style="margin-top:20px">${table(['İş','Öğrenci / sınav','Durum','Çağrı','Hata / işlem'],queue.items.map(q=>[esc(({whole_optical:'Tam optik',mock_key:'Deneme anahtarı',homework_key:'Ödev anahtarı',submission:'Teslim değerlendirme'}[q.kind])||q.kind),esc(name('students',q.student_id)||name('exams',q.exam_id)),badge(q.status),q.provider_calls||0,`${esc(q.error||'')}${['FAILED','UNCERTAIN'].includes(q.status)?btn('retry-ai','Tekrar kuyruğa al',`data-id="${q.id}"`):''}`]))}</div></section><section class="panel"><h2>Ödev değerlendirmeleri</h2><div style="margin-top:20px">${table(['Öğrenci','Ödev','D / Y / B','Net','Güven','Durum','İşlem'],evaluations.items.map(e=>[esc(name('students',e.student_id)),esc(name('homework',e.homework_id)),`${e.correct} / ${e.wrong} / ${e.blank}`,e.net,`${Math.round(e.confidence*100)}%`,badge(e.status),btn('review-evaluation','İncele / düzelt',`data-id="${e.id}"`)]))}</div></section><section class="panel"><h2>Cevap anahtarları</h2><div style="margin-top:20px">${table(['Ödev','Durum','Güven','İşlem'],keys.items.map(k=>[esc(name('homework',k.homework_id)),badge(k.status),`${Math.round((k.confidence||0)*100)}%`,btn('homework-key','Düzelt / onayla',`data-id="${k.homework_id}"`)]))}</div></section>`}
async function whatsappPage(c){const [queue,settings]=await Promise.all([api('/whatsapp/queue?limit=100'),api('/settings')]);S.waQueue=queue.items;c.innerHTML=heading('WhatsApp','Tarihli iletişim izni, onaylı Meta şablonu ve kontrollü gönderim.',btn('new','Şablon ekle','data-kind="templates"')+btn('queue-whatsapp','Mesaj hazırla','','primary'))+`<div class="alert">${settings.credentials.whatsapp?'Meta bağlantısı tanımlı.':'Meta bağlantısı için erişim tokenı ve telefon numarası kimliği gerekli.'} Gönderim ${settings.values.WHATSAPP_ENABLED==='true'?'açık':'kapalı'}. Her mesaj ayrı gönderilir; aynı bağlam tekrar gönderilmez.</div><section class="panel"><h2>Mesaj kuyruğu</h2><div style="margin-top:20px">${table(['Alıcı','Şablon','Bağlam','Durum','İşlem'],queue.items.map(q=>[`${esc(name('students',q.student_id))}<div class="meta">${esc(q.phone)}</div>`,esc(name('templates',q.template_id)),esc(q.context),`${badge(q.status)}<div class="meta">${esc(q.error||q.provider_id||'')}</div>`,q.status==='QUEUED'?btn('send-whatsapp','Bu mesajı gönder',`data-id="${q.id}"`,'primary'):q.status==='FAILED'?btn('retry-whatsapp','Tekrar kuyruğa al',`data-id="${q.id}"`):'—']))}</div></section><section class="panel"><h2>Şablonlar</h2><div style="margin-top:20px">${table(['Ad','Meta adı','Dil','İşlem'],(S.meta.templates||[]).map(t=>[esc(t.name),esc(t.provider_name),esc(t.language),rowActions('templates',t)]))}</div></section>`}
async function examsPage(c){const [exams,results,optics]=await Promise.all([api('/mock-exams?limit=500'),api('/mock-results?limit=500'),api('/mock-optics?limit=500')]);S.meta.exams=exams.items;S.results=results.items;S.optics=optics.items;S.items=exams.items;c.innerHTML=heading('Deneme Kulübü','TYT ve AYT · tam optik · tek okuma · tek karne.',btn('new','Sınav oluştur','data-kind="mock-exams"','primary'))+`<div class="cards">${card('Sınav',exams.total)}${card('Karne',results.total)}${card('Kontrol bekleyen',results.items.filter(r=>r.status==='REVIEW').length)}${card('Ortalama net',results.items.length?(results.items.reduce((a,r)=>a+r.report.totals.net,0)/results.items.length).toFixed(2):'—')}</div><section class="panel">${table(['Sınav','Tür / tarih','Anahtar','Karne','İşlem'],exams.items.map(e=>[esc(e.name),`${esc(S.catalog.formats[e.kind]?.label)}<div class="meta">${esc(e.date)}</div>`,badge(e.status),results.items.filter(r=>r.exam_id===e.id).length,btn('exam-key','Anahtar',`data-id="${e.id}"`)+btn('whole-optical','Tam optik',`data-id="${e.id}"`)+btn('batch-optical','Toplu optik',`data-id="${e.id}"`)+btn('exam-results','Karneler / analiz',`data-id="${e.id}"`)+rowActions('mock-exams',e)]))}</section><section class="panel"><h2>Optik kontrol kuyruğu</h2><div style="margin-top:20px">${table(['Öğrenci','Sınav','Güven','Optik','İşlem'],optics.items.filter(o=>o.status==='REVIEW').map(o=>[esc(name('students',o.student_id)),esc(name('exams',o.exam_id)),`${Math.round(o.confidence*100)}%`,linkFile(o.file_id),btn('review-optical','İncele / düzelt',`data-id="${o.id}"`)]))}</div></section>`}
function resultCard(r){const p=r.report;return `<div class="print-head"><h2>ANA PRG · Deneme karnesi</h2></div><p class="muted">${esc(p.student.name)} · ${esc(p.exam.name)} · ${esc(p.exam.date)}</p><div class="result-total"><strong>${p.totals.net}</strong><span>toplam net</span>${badge(r.status)}</div><div style="margin-top:22px">${table(['Ders','D','Y','B','Net'],Object.values(p.subjects).map(s=>[esc(s.label),s.correct,s.wrong,s.blank,s.net]).concat([['<strong>Toplam</strong>',p.totals.correct,p.totals.wrong,p.totals.blank,`<strong>${p.totals.net}</strong>`]]))}</div><div class="grid" style="margin-top:23px"><div class="card"><div class="label">Demo sıra / puan</div><div class="number">${p.demo.rank.toLocaleString('tr-TR')}</div><p>${p.demo.score} puan · ${p.demo.participants.toLocaleString('tr-TR')} demo katılımcı</p><div class="small muted">Üstten %${p.demo.percentile_from_top}</div></div><div class="card"><div class="label">2026 eşdeğeri · tahmini sıra</div><div class="number">${p.estimate.rank.toLocaleString('tr-TR')}</div><p>${p.estimate.score} tahmini puan</p><div class="small muted">Üstten %${p.estimate.percentile_from_top}${p.estimate.paired_tyt_exam_id?' · Önceki TYT ile birleşik':''}</div></div></div><p class="result-note">${esc(p.calculation_note)} ${esc(p.estimate.note)}</p>`}
async function showResults(id){const data=await api('/mock-exams/'+id+'/results');S.examAnalysis=data;modal(data.exam.name+' · Sonuçlar',`<div class="actions"><a class="button" href="${API}/mock-exams/${id}/export.csv">UTF-8 CSV indir</a></div><div style="margin-top:20px">${table(['Öğrenci','Net','Demo sıra','Durum','Karne'],data.leaderboard.map(r=>[esc(r.report.student.name),r.report.totals.net,r.report.demo.rank,badge(r.status),btn('result-card','Karneyi aç',`data-id="${r.id}"`)]))}</div><h3 style="margin-top:25px">Soru analizi</h3><p class="muted small">P-index doğru oranıdır. Ayırt edicilik en az 4 optikte hesaplanır.</p>${table(['Ders / soru','Doğru','Yanlış','Boş','P-index','Ayırt edicilik'],data.item_analysis.map(i=>[esc(i.subject)+' / '+i.question,i.correct,i.wrong,i.blank,i.p_index.toFixed(3),i.discrimination===null?'Yetersiz veri':i.discrimination.toFixed(3)]))}`)}
async function reportsPage(c){S.reportWeek=S.reportWeek||'';const r=await api('/reports'+(S.reportWeek?'?week='+S.reportWeek:''));S.report=r;const sorted=r.mock_results.slice().sort((a,b)=>a.report.exam.date.localeCompare(b.report.exam.date));c.innerHTML=heading('Raporlar','Haftalık tamamlama, ders dağılımı, AI sonuçları ve deneme geçmişi.',`<a class="button" href="${API}/reports/export.csv${S.reportWeek?'?week='+S.reportWeek:''}">CSV indir</a>`+btn('print','Yazdır')+btn('report-snapshot','Raporu kaydet','','primary'))+`<div class="toolbar"><label>Hafta filtresi <input type="date" id="report-week" value="${esc(S.reportWeek)}"></label>${btn('report-all','Tüm haftalar')}</div><section class="panel"><h2>Öğrenci tamamlama</h2><div style="margin-top:20px">${table(['Öğrenci','Atama','Teslim','Tamamlama','Dersler'],r.students.map(x=>[esc(x.name),x.assigned,x.submitted,`${Math.round(100*x.submitted/x.assigned)}%`,esc(Object.entries(x.courses).map(([k,v])=>course(k)+': '+v).join(', '))]))}</div></section><section class="panel"><h2>Deneme net trendi</h2>${spark(sorted)}</section><section class="panel"><h2>Deneme geçmişi</h2><div style="margin-top:20px">${table(['Öğrenci','Sınav','Tarih','Net','Durum','Karne'],sorted.map(x=>[esc(x.report.student.name),esc(x.report.exam.name),esc(x.report.exam.date),x.report.totals.net,badge(x.status),btn('report-card','Karne',`data-id="${x.id}"`)]))}</div></section>`}
const settingLabels={AI_MODEL:'AI modeli',AI_MONTHLY_BUDGET_TL:'AI aylık bütçe (TL)',WHATSAPP_MONTHLY_BUDGET_TL:'WhatsApp aylık bütçe (TL)',USDTRY_RATE:'Bütçe için USD/TL',WHATSAPP_ENABLED:'WhatsApp gönderimi',SHADOW_MODE:'Gölge modu (dış çağrıları kapatır)',AUTO_GENERATE_ENABLED:'Otomatik haftalık program',AUTO_AI_ENABLED:'AI kuyruğunu otomatik çalıştır',AI_JOB_LIMIT:'Her çalıştırmada AI iş sayısı',WHATSAPP_MESSAGE_ESTIMATE_TL:'Mesaj başına tahmini maliyet (TL)',AI_INPUT_USD_PER_MILLION:'AI giriş maliyeti (USD / 1M token)',AI_OUTPUT_USD_PER_MILLION:'AI çıkış maliyeti (USD / 1M token)'};
async function settingsPage(c){const x=await api('/settings');S.settings=x;c.innerHTML=heading('Ayarlar','Servisler, bütçe ve otomatik çalışma tercihleri.')+`<div class="cards">${card('OpenAI bağlantısı',x.credentials.openai?'Tanımlı':'Eksik')}${card('Meta WhatsApp',x.credentials.whatsapp?'Tanımlı':'Eksik')}</div><form id="settings-form" class="panel"><h2>Çalışma tercihleri</h2>${Object.entries(settingLabels).map(([k,l])=>{const bool=k.endsWith('_ENABLED')||k==='SHADOW_MODE',v=x.values[k]??(bool?'false':k==='WHATSAPP_MESSAGE_ESTIMATE_TL'?'2':'');return `<div class="settings-row"><label for="setting-${k}">${esc(l)}</label>${bool?`<select id="setting-${k}" name="${k}"><option value="true" ${v==='true'?'selected':''}>Açık</option><option value="false" ${v!=='true'?'selected':''}>Kapalı</option></select>`:`<input id="setting-${k}" name="${k}" value="${esc(v)}" type="${k==='AI_MODEL'?'text':'number'}" ${k==='AI_MODEL'?'':'step="0.01" min="0"'} required>`}</div>`}).join('')}<p class="muted small" style="margin-top:20px">Gölge modu açıkken AI ve WhatsApp çağrıları gönderilmez. WhatsApp gönderimi ayrıca etkinleştirilmelidir.</p><div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Ayarları kaydet</button></div></form><form id="password-form" class="panel"><h2>Yönetici şifresi</h2><p class="muted">GENESIS ve ANA PRG aynı öğretmen hesabını kullanır. Şifre değişince öğretmen oturumları kapatılır.</p><div class="settings-row"><label for="password-current">Mevcut şifre</label><input id="password-current" name="current_password" type="password" autocomplete="current-password" required></div><div class="settings-row"><label for="password-new">Yeni şifre</label><input id="password-new" name="new_password" type="password" autocomplete="new-password" minlength="12" required></div><div class="settings-row"><label for="password-confirm">Yeni şifre tekrarı</label><input id="password-confirm" name="confirmation" type="password" autocomplete="new-password" minlength="12" required></div><div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Yönetici şifresini değiştir</button></div></form>`}
async function systemPage(c){const [health,logs,costs]=await Promise.all([api('/system/health'),api('/system/logs'),api('/costs?limit=100')]);c.innerHTML=heading('Sistem Yönetimi','Kalıcı veri, servis maliyetleri ve operasyon kayıtları.',btn('persist','Kalıcılığı doğrula','','primary'))+`<div class="cards">${card('SQLite',health.ok?'Sağlıklı':'Hata')}${card('Son R2 kaydı',health.last_sync?.slice(11,19)||'—',health.last_sync?.slice(0,10)||'')}${card('Restore',health.restored?'R2’den döndü':'Yeni alan')}${card('Hata',health.last_error||'Yok')}</div><section class="panel"><h2>Servis maliyetleri</h2><div style="margin-top:20px">${table(['Servis','Durum','Tutar (TL)','Tarih'],costs.items.map(r=>[esc(r.provider),esc(r.status),Number(r.tl||0).toFixed(4),esc(r.created_at)]))}</div></section><section class="panel"><h2>İşlem kayıtları</h2><div style="margin-top:20px">${table(['Zaman','Kullanıcı','İşlem','Kayıt'],logs.items.map(r=>[esc(r.created_at),esc(r.actor),esc(r.event),esc(r.entity_id)]))}</div></section>`}
function fileForm(category,student=false){modal('Dosya yükle',`<form id="upload-form" data-category="${category}"><div class="form-grid"><div class="field wide"><label>PDF, PNG veya JPEG · en fazla 20 MB</label><input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required></div>${student?'':field(['student_id','İlgili öğrenci (varsa)','students'])}</div><div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Yükle ve doğrula</button></div></form>`)}
async function uploadFile(file,category,studentId=''){if(file.size>20*1024*1024)throw new Error('Dosya en fazla 20 MB olabilir.');const form=new FormData();form.set('file',file);form.set('category',category);if(studentId)form.set('student_id',studentId);return api('/files/upload','POST',form)}
function answerInputs(subjects,answers={}){return subjects.map(s=>`<section class="key-subject"><h3>${esc(s.label)} · ${s.q} soru</h3><div class="key-grid">${Array.from({length:s.q},(_,i)=>`<div class="key-cell"><label>${i+1}</label><select data-answer="${s.code}" data-question="${i+1}"><option value="">Boş</option>${'ABCDE'.split('').map(a=>`<option value="${a}" ${answers[s.code]?.[i]===a?'selected':''}>${a}</option>`).join('')}</select></div>`).join('')}</div><div class="toolbar" style="margin-top:12px"><input placeholder="Toplu yapıştır: A B C…" data-paste="${s.code}" aria-label="${esc(s.label)} cevaplarını yapıştır">${btn('paste-answers','Uygula',`data-subject="${s.code}"`)}</div></section>`).join('')}
function readAnswers(form){const key={};for(const input of form.querySelectorAll('[data-answer]')){(key[input.dataset.answer]??=[])[Number(input.dataset.question)-1]=input.value}return key}
async function keyEditor(id){const exam=S.meta.exams.find(e=>e.id===id),data=await api('/mock-exams/'+id+'/answer-key'),subjects=S.catalog.formats[exam.kind].subjects;modal('Cevap anahtarı · '+exam.name,`<div class="actions">${btn('key-ai','Anahtar görselini Luna ile oku',`data-id="${id}"`)}</div>${Object.keys(data.ai_key).length?'<p class="alert" style="margin-top:15px">AI anahtarı taslaktır. Bütün cevapları kontrol edip onaylayın.</p>':''}<form id="exam-key-form" data-id="${id}">${answerInputs(subjects,Object.keys(data.ai_key).length?data.ai_key:data.key)}<div class="form-error" role="alert"></div><div class="dialog-footer"><button type="submit" class="primary">Anahtarı onayla ve karneleri güncelle</button></div></form>`)}
async function homeworkKeyEditor(id){const h=S.meta.homework.find(h=>h.id===id),rows=await api('/answer-keys?limit=500'),key=rows.items.find(x=>x.homework_id===id);modal('Ödev anahtarı · '+h.name,`<div class="actions">${btn('homework-key-ai','PDF / referanstan Luna ile oku',`data-id="${id}"`)}</div><form id="homework-key-form" data-id="${id}">${answerInputs([{code:'HOMEWORK',label:h.name,q:h.questions}],{HOMEWORK:key?.answers||[]})}<div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Anahtarı onayla</button></div></form>`)}
function wholeOptical(id,batch=false){const exam=S.meta.exams.find(e=>e.id===id);modal((batch?'Toplu tam optik':'Tam optik')+' · '+exam.name,`<p class="muted">Her öğrenci için bütün bölümleri içeren tek PNG/JPEG yükleyin. Her dosya tek AI çağrısında okunur.</p><form id="${batch?'batch-optical-form':'whole-optical-form'}" data-id="${id}">${batch?'':field(['student_id','Öğrenci','students',true])}<div class="field" style="margin-top:18px"><label>${batch?'Birden fazla tam optik':'Tek tam optik'}</label><input name="file" type="file" accept="image/png,image/jpeg" ${batch?'multiple':''} required></div>${batch?'<div id="batch-mapping" style="margin-top:20px"></div>':''}<div class="form-error" role="alert"></div><div class="dialog-footer"><button type="submit" class="primary">${batch?'Eşlemeleri kuyruğa al':'Tüm optiği oku ve karne oluştur'}</button></div></form>`)}
function aiQueueEditor(){modal('AI işi ekle',`<form id="ai-job-form"><div class="form-grid"><div class="field"><label>İş türü</label><select name="kind"><option value="homework_key">Ödev cevap anahtarı</option><option value="submission">Teslim değerlendirme</option><option value="mock_key">Deneme cevap anahtarı</option></select></div>${field(['homework_id','Ödev','homework'])}${field(['exam_id','Deneme sınavı','exams'])}${field(['file_id','Okunacak dosya','files'])}<div class="field wide"><label>Teslim kimliği (teslim değerlendirmesi için)</label><input name="submission_id"></div></div><div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Kuyruğa al</button></div></form>`)}
function queueWhatsapp(){modal('WhatsApp mesajı hazırla',`<form id="wa-queue-form"><div class="form-grid">${field(['student_id','Öğrenci','students',true])}${field(['template_id','Onaylı şablon','templates',true])}<div class="field"><label>Veli (boşsa öğrencinin telefonu)</label><select name="guardian_id"><option value="">Öğrenci</option>${(S.meta.guardians||[]).map(g=>`<option value="${g.id}">${esc(g.name)} · ${esc(name('students',g.student_id))}</option>`).join('')}</select></div>${field(['context','Tekrarlı gönderim bağlamı (örn. 2026-10-05 haftalık rapor)','text',true])}<div class="field wide"><label>Şablon parametreleri · her satıra bir değer</label><textarea name="parameters"></textarea></div></div><div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Göndermeden kuyruğa al</button></div></form>`)}
async function studentPage(){const d=await api('/student/me');S.student=d;const results=d.results.slice().sort((a,b)=>a.report.exam.date.localeCompare(b.report.exam.date));app.innerHTML=`<header class="student-top"><a class="brand" href="/ana-prg/student">ANA PRG<small>ÖĞRENCİ PORTALI</small></a><div class="actions"><span>${esc(d.student.name)}</span>${btn('refresh','Yenile','','quiet')}${btn('logout','Çıkış','','quiet')}</div></header><main class="student-body">${heading('Merhaba, '+d.student.name,'Çalışma programınız ve sonuçlarınız burada.')}<div class="cards">${card('Atama',d.assignments.length)}${card('Teslim',d.submissions.length)}${card('Deneme',d.results.length)}${card('Seçili ders',d.student.courses.length)}</div><div class="student-tabs">${[['program','Program & Ödevler'],['evaluations','AI Sonuçları'],['results','Deneme Geçmişi'],['videos','Çözüm Videoları']].map(([id,label])=>btn('student-tab',label,`data-tab="${id}"`,S.studentTab===id?'active':'quiet')).join('')}</div><section class="panel">${S.studentTab==='program'?table(['Tarih / ders','Ödev','Durum','Dosya','Teslim'],d.assignments.map(a=>{const h=d.homework.find(h=>h.id===a.homework_id);return[`${esc(a.date)}<div class="meta">${esc(course(a.course))}</div>`,esc(h?.name||a.homework_id),badge(a.status),linkFile(h?.file_id),btn('student-submit','Teslim et',`data-id="${a.id}"`)]})):S.studentTab==='evaluations'?table(['Ödev','D / Y / B','Net','Geri bildirim'],d.evaluations.map(e=>[esc(d.homework.find(h=>h.id===e.homework_id)?.name),`${e.correct} / ${e.wrong} / ${e.blank}`,e.net,esc(e.feedback)])):S.studentTab==='results'?`<h2>Net trendi</h2>${spark(results)}${table(['Sınav','Tarih','Net','Karne'],results.map(r=>[esc(r.report.exam.name),esc(r.report.exam.date),r.report.totals.net,btn('student-result','Karneyi aç',`data-id="${r.id}"`)]))}`:table(['Video','Ders','İzle'],d.videos.map(v=>[esc(v.name),esc(course(v.course)),`<a href="${esc(v.url)}" target="_blank" rel="noopener">İzle ↗</a>`]))}</section><p class="small muted">AI/optik sonuçları öğretmen kontrolünden sonra görünür. PIN’inizi paylaşmayın.</p></main>`}
async function refresh(){if(S.session?.role==='STUDENT')return studentPage();await metadata();return render()}
function confirmAction(title,message,action,extra=''){modal(title,`<p class="muted">${esc(message)}</p>`,`<div class="dialog-footer">${btn('close','Vazgeç','','quiet')}${btn(action,'Onayla',extra,'primary')}</div>`)}
document.addEventListener('click',async event=>{const anchor=event.target.closest('[data-nav]');if(anchor){event.preventDefault();await navigate(anchor.dataset.nav);return}const b=event.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id,kind=b.dataset.kind;try{
 if(a==='close'){close();return}if(a==='menu'){document.querySelector('.shell')?.classList.toggle('nav-open');return}if(a==='reload'){location.reload();return}
 if(a==='logout'){await api('/auth/logout','POST',{});S.session=null;login(S.page==='student');return}
 if(a==='nav'){await navigate(b.dataset.page);return}if(a==='refresh'){await busy(b,refresh);return}
 if(a==='new'){editor(kind);return}if(a==='edit'){const data=await api('/'+defs[kind].path+'?limit=500');editor(kind,data.items.find(x=>x.id===id));return}
 if(a==='archive'){confirmAction('Kaydı arşivle','Kayıt geçmişi korunacak. Aktif kullanımda görünmeyecek.','archive-confirm',`data-kind="${kind}" data-id="${id}"`);return}
 if(a==='archive-confirm'){await busy(b,()=>api('/'+defs[kind].path+'/'+id,'DELETE',{}));close();notice('Kayıt arşivlendi.');await refresh();return}
 if(a==='upload'){fileForm(b.dataset.category);return}
 if(a==='page-prev'){S.offset=Math.max(0,S.offset-100);await render();return}if(a==='page-next'){if(S.offset+100<Number(b.dataset.total))S.offset+=100;await render();return}
 if(a==='program-preview'||a==='program-generate'){const result=await busy(b,()=>api('/programs/generate','POST',{week:S.week,preview:a==='program-preview',skip_past:true}));if(a==='program-preview')modal('Program önizlemesi',table(['Tarih','Ders','Ödev'],result.slots.map(x=>[esc(x.date),esc(course(x.course)),esc(name('homework',x.homework_id))])));else{notice(`${result.created} hücre, ${result.assignments} yeni atama oluşturuldu.`);await refresh()}return}
 if(a==='program-sync'||a==='program-next'){const r=await busy(b,()=>api('/programs/'+(a==='program-sync'?'sync':'next-week'),'POST',{week:S.week}));notice(`İşlem tamamlandı; ${r.created||0} yeni kayıt.`);if(a==='program-next'){const d=new Date(S.week+'T12:00:00');d.setDate(d.getDate()+7);S.week=d.toISOString().slice(0,10)}await refresh();return}
 if(a==='program-reset'){confirmAction('Otomatik haftayı sıfırla','Yalnız otomatik hücreler arşivlenir. Teslimi bulunan atamalar korunur.','program-reset-confirm');return}
 if(a==='program-reset-confirm'){await busy(b,()=>api('/programs/reset','POST',{week:S.week}));close();await refresh();return}
 if(a==='program-slot'){const choices=S.meta.homework.filter(h=>h.course===b.dataset.course);modal('Program hücresi · '+course(b.dataset.course),`<form id="slot-form" data-day="${b.dataset.day}"><label>Ödev</label><select name="homework_id" required><option value="">Seçin</option>${choices.map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join('')}</select><div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Kaydet ve senkronla</button></div></form>`);return}
 if(a==='queue-ai'){aiQueueEditor();return}if(a==='run-ai'){await busy(b,()=>api('/ai/run','POST',{limit:3}));notice('AI kuyruğu başlatıldı. Durumları yenileyin.');return}
 if(a==='retry-ai'){const q=S.aiQueue.find(q=>q.id===id);confirmAction('AI işini tekrar dene',q.status==='UNCERTAIN'?'Önceki çağrının sonucu belirsiz. Tekrar çağrı ek ücret oluşturabilir.':'Başarısız işi tekrar kuyruğa alın.','retry-ai-confirm',`data-id="${id}"`);return}
 if(a==='retry-ai-confirm'){await busy(b,()=>api('/ai/queue/'+id+'/retry','POST',{confirmed:true}));close();await refresh();return}
 if(a==='submission-ai'){await busy(b,()=>api('/ai/queue','POST',{kind:'submission',submission_id:id}));notice('Teslim AI kuyruğuna alındı.');return}
 if(a==='homework-key'){await homeworkKeyEditor(id);return}
 if(a==='homework-key-ai'){const h=S.meta.homework.find(h=>h.id===id);modal('Anahtar dosyasını seç',`<form id="key-ai-form" data-kind="homework_key" data-id="${id}">${field(['file_id','PDF / referans dosyası','files',true],h.file_id)}<div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Luna kuyruğuna al</button></div></form>`);return}
 if(a==='exam-key'){await keyEditor(id);return}if(a==='key-ai'){modal('Deneme anahtarı görseli',`<form id="key-image-form" data-id="${id}"><label>Tek anahtar PNG/JPEG (tüm dersler)</label><input type="file" name="file" accept="image/png,image/jpeg" required><div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Luna ile oku</button></div></form>`);return}
 if(a==='whole-optical'||a==='batch-optical'){wholeOptical(id,a==='batch-optical');return}
 if(a==='exam-results'){await busy(b,()=>showResults(id));return}
 if(a==='result-card'||a==='report-card'||a==='student-result'){const r=a==='result-card'?S.examAnalysis.results.find(r=>r.id===id):a==='report-card'?S.report.mock_results.find(r=>r.id===id):await api('/student/me/results/'+id);modal('Deneme karnesi',resultCard(r),`<div class="dialog-footer">${btn('print','Yazdır')}</div>`);return}
 if(a==='review-optical'){const o=S.optics.find(o=>o.id===id),exam=S.meta.exams.find(e=>e.id===o.exam_id),key={};for(const x of o.answers)(key[x.subject]??=[])[x.question_no-1]=x.answer;modal('Optik kontrolü · '+name('students',o.student_id),`${linkFile(o.file_id)}<form id="optical-review-form" data-id="${id}">${answerInputs(S.catalog.formats[exam.kind].subjects,key)}<div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Düzeltmeleri onayla ve karne oluştur</button></div></form>`);return}
 if(a==='review-evaluation'){const e=S.evaluations.find(e=>e.id===id);modal('AI değerlendirmesi · '+name('students',e.student_id),`<p class="muted">${esc(e.feedback)}</p><form id="evaluation-review-form" data-id="${id}">${answerInputs([{code:'HOMEWORK',label:name('homework',e.homework_id),q:e.answers.length}],{HOMEWORK:e.answers})}<div class="form-error" role="alert"></div><div class="dialog-footer"><button class="primary" type="submit">Düzelt ve onayla</button></div></form>`);return}
 if(a==='paste-answers'){const input=dialog.querySelector(`[data-paste="${b.dataset.subject}"]`),answers=input.value.toUpperCase().split(/[\s,;]+/).filter(Boolean),selects=dialog.querySelectorAll(`[data-answer="${b.dataset.subject}"]`);if(answers.length!==selects.length||answers.some(x=>!['A','B','C','D','E','_'].includes(x)))throw new Error(`${selects.length} cevap girin; boş için _ kullanın.`);selects.forEach((s,i)=>s.value=answers[i]==='_'?'':answers[i]);return}
 if(a==='queue-whatsapp'){queueWhatsapp();return}
 if(a==='send-whatsapp'){const row=S.waQueue.find(q=>q.id===id);confirmAction('WhatsApp gönderimini onayla',`${name('students',row.student_id)} · ${row.phone} numarasına yalnız bu mesaj gönderilecek.`,'send-whatsapp-confirm',`data-id="${id}"`);return}
 if(a==='send-whatsapp-confirm'){await busy(b,()=>api('/whatsapp/queue/'+id+'/send','POST',{}));close();notice('Mesaj sağlayıcıya gönderildi.');await refresh();return}
 if(a==='retry-whatsapp'){await busy(b,()=>api('/whatsapp/queue/'+id+'/retry','POST',{}));await refresh();return}
 if(a==='report-snapshot'){await busy(b,()=>api('/reports/snapshot','POST',{week:S.reportWeek||null}));notice('Rapor kaydedildi.');return}if(a==='report-all'){S.reportWeek='';await render();return}
 if(a==='persist'){await busy(b,()=>api('/system/persist','POST',{}));notice('ANA PRG R2 kaydı doğrulandı.');await refresh();return}
 if(a==='print'){window.print();return}
 if(a==='student-tab'){S.studentTab=b.dataset.tab;await studentPage();return}
 if(a==='student-submit'){modal('Ödevi teslim et',`<form id="student-submit-form" data-id="${id}"><label>Çalışmanız · PDF/PNG/JPEG · en fazla 20 MB</label><input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required><label style="margin-top:17px">Not</label><textarea name="note"></textarea><div class="form-error" role="alert"></div><div class="dialog-footer"><button type="submit" class="primary">Teslim et</button></div></form>`);return}
 if(a==='extra-list'){const r=await api('/'+kind+'?limit=500');modal(defs[kind].title,table(['Kayıt','Ders / konu','İşlem'],r.items.map(x=>[esc(x.name||x.topic),esc(course(x.course)),rowActions(kind,x)])));return}
}catch(e){notice(e.message,true)}});
document.addEventListener('submit',async event=>{const form=event.target;if(!(form instanceof HTMLFormElement))return;event.preventDefault();const b=form.querySelector('button[type=submit]'),fd=new FormData(form),values=Object.fromEntries(fd.entries());form.querySelector('.form-error')?.replaceChildren();try{await busy(b,async()=>{
 if(form.id==='login-form'){const student=form.dataset.student==='true';S.session=await api(student?'/student/auth/login':'/auth/teacher-login','POST',student?{code:values.code,pin:values.password}:{username:values.code,password:values.password});await boot();return}
 if(form.id==='search-form'){S.search=values.search;S.offset=0;await render();return}
 if(form.id==='editor-form'){const kind=form.dataset.kind,def=defs[kind],payload={};for(const [key,label,type] of def.fields){if(type==='courses'||type==='days')payload[key]=fd.getAll(key).map(x=>type==='days'?Number(x):x);else if(type==='checkbox')payload[key]=fd.has(key);else if(type==='number')payload[key]=Number(values[key]||0);else if(key==='pin'&&!values[key])continue;else payload[key]=values[key]||''}if(!form.dataset.id&&kind==='students'&&!payload.pin)throw new Error('Öğrenci için en az 4 karakter PIN girin.');await api('/'+def.path+(form.dataset.id?'/'+form.dataset.id:''),form.dataset.id?'PATCH':'POST',payload);close();notice('Kayıt kaydedildi.');await refresh();return}
 if(form.id==='upload-form'){const file=await uploadFile(fd.get('file'),form.dataset.category,values.student_id);close();notice('Dosya SHA-256 ile doğrulandı.');await metadata();if(form.dataset.category==='homework')editor('homework',{file_id:file.id,name:file.name.replace(/\.pdf$/i,''),questions:1,order:1});return}
 if(form.id==='slot-form'){await api('/programs/slot','POST',{week:S.week,day:Number(form.dataset.day),homework_id:values.homework_id});close();await refresh();return}
 if(form.id==='ai-job-form'){await api('/ai/queue','POST',values);close();notice('AI işi kuyruğa alındı.');await refresh();return}
 if(form.id==='key-ai-form'){await api('/ai/queue','POST',{kind:form.dataset.kind,homework_id:form.dataset.id,file_id:values.file_id});close();notice('Anahtar okuma kuyruğa alındı.');return}
 if(form.id==='key-image-form'){const file=await uploadFile(fd.get('file'),'answer-keys');await api('/ai/queue','POST',{kind:'mock_key',exam_id:form.dataset.id,file_id:file.id});close();notice('Anahtar görseli AI kuyruğuna alındı.');await refresh();return}
 if(form.id==='exam-key-form'){await api('/mock-exams/'+form.dataset.id+'/answer-key','POST',{key:readAnswers(form)});close();notice('Cevap anahtarı onaylandı.');await refresh();return}
 if(form.id==='homework-key-form'){await api('/homework/'+form.dataset.id+'/answer-key','POST',{answers:readAnswers(form).HOMEWORK});close();notice('Ödev anahtarı onaylandı.');await refresh();return}
 if(form.id==='whole-optical-form'){const file=await uploadFile(fd.get('file'),'optics',values.student_id);await api('/mock-exams/'+form.dataset.id+'/optics/whole','POST',{file_id:file.id,student_id:values.student_id});close();notice('Tam optik AI kuyruğuna alındı. AI ekranından çalıştırabilirsiniz.');await refresh();return}
 if(form.id==='batch-optical-form'){const files=Array.from(form.querySelector('[name=file]').files),mapping=Array.from(form.querySelectorAll('[data-batch-index]'));if(!files.length||files.length>50||mapping.length!==files.length)throw new Error('1–50 optik için öğrenci eşlemelerini seçin.');if(mapping.some(m=>!m.value))throw new Error('Her dosyaya öğrenci seçin.');const items=[];for(let i=0;i<files.length;i++){const file=await uploadFile(files[i],'optics',mapping[i].value);items.push({student_id:mapping[i].value,file_id:file.id})}const result=await api('/mock-exams/'+form.dataset.id+'/optics/batch','POST',{items});const failed=result.items.filter(r=>r.error);if(failed.length){form.querySelector('.form-error').textContent=failed.map(r=>name('students',r.student_id)+': '+r.error).join('\n');notice(`${result.items.length-failed.length} kuyruğa alındı; ${failed.length} hata.`,true)}else{close();notice('Toplu optikler kuyruğa alındı.');await refresh()}return}
 if(form.id==='optical-review-form'){const key=readAnswers(form),answers=Object.entries(key).flatMap(([subject,arr])=>arr.map((answer,i)=>({subject,question_no:i+1,answer})));await api('/mock-optics/'+form.dataset.id+'/approve','POST',{answers});close();notice('Optik düzeltildi; karne onaylandı.');await refresh();return}
 if(form.id==='evaluation-review-form'){await api('/evaluations/'+form.dataset.id+'/review','POST',{answers:readAnswers(form).HOMEWORK});close();notice('Değerlendirme düzeltildi ve onaylandı.');await refresh();return}
 if(form.id==='wa-queue-form'){await api('/whatsapp/queue','POST',{...values,parameters:values.parameters.split('\n').filter(Boolean)});close();notice('Mesaj gönderilmeden kuyruğa alındı.');await refresh();return}
 if(form.id==='password-form'){if(values.new_password!==values.confirmation)throw new Error('Yeni şifreler eşleşmiyor.');await api('/auth/change-password','POST',{current_password:values.current_password,new_password:values.new_password});close();S.session=null;await boot();notice('Şifre değiştirildi. Yeni şifrenizle giriş yapın.');return}
 if(form.id==='settings-form'){await api('/settings','PATCH',values);notice('Ayarlar kaydedildi.');await refresh();return}
 if(form.id==='student-submit-form'){const file=await uploadFile(fd.get('file'),'submissions');await api('/submissions','POST',{assignment_id:form.dataset.id,file_id:file.id,note:values.note});close();notice('Ödev teslim edildi.');await studentPage();return}
})}catch(e){const target=form.querySelector('.form-error')||document.querySelector('#login-error');if(target)target.textContent=e.message}});
document.addEventListener('change',async event=>{try{if(event.target.id==='week-input'){S.week=event.target.value;await render()}if(event.target.id==='report-week'){S.reportWeek=event.target.value;await render()}if(event.target.matches('#batch-optical-form [name=file]')){const files=Array.from(event.target.files);document.querySelector('#batch-mapping').innerHTML=files.map((f,i)=>`<div class="settings-row"><label>${esc(f.name)}</label><select data-batch-index="${i}" required>${options('students','')}</select></div>`).join('')}}catch(e){notice(e.message,true)}});
window.addEventListener('popstate',boot);
boot();

function field(spec,value){if(['days','courses','checkbox'].includes(spec[2]))return rawField(spec,value);const id='field-'+spec[0];return rawField(spec,value).replace('<label>','<label for="'+id+'">').replace(/<(input|select|textarea) /,'<$1 id="'+id+'" ')}
