const fs=require("fs"),path=require("path"),crypto=require("crypto"),cp=require("child_process"),http=require("http"),https=require("https");
const ROOT=path.resolve(__dirname,".."), APP=path.join(ROOT,"app"), RUNTIME=path.join(ROOT,"runtime"), LOGS=path.join(ROOT,"logs"), CONFIG=path.join(ROOT,"config");
fs.mkdirSync(RUNTIME,{recursive:true}); fs.mkdirSync(LOGS,{recursive:true});
const session=new Date().toISOString().replace(/\D/g,"").slice(0,14);
const slog=path.join(LOGS,`session_node_${session}.log`);
function log(level,msg){const line=`${new Date().toISOString()} [${level}] ${msg}`; console.log(line); fs.appendFileSync(slog,line+"\r\n");}
function run(cmd,args=[],opts={}){return cp.spawnSync(cmd,args,{encoding:"utf8",windowsHide:true,...opts});}
function existsCmd(cmd,args=["--version"]){try{return run(cmd,args).status===0}catch{return false}}
function sha256(p){return crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex")}
function parseJson(s){return JSON.parse(String(s).replace(/^\uFEFF/,""))}
function fetchBuffer(url,timeout=20000){return new Promise((resolve,reject)=>{const lib=url.startsWith("https:")?https:http; const r=lib.get(url,{headers:{"User-Agent":"YILBAY-BOOTSTRAP-NODE"}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume(); return fetchBuffer(new URL(res.headers.location,url).toString(),timeout).then(resolve,reject)} if(res.statusCode!==200){res.resume();return reject(new Error(`HTTP ${res.statusCode}`))} const a=[];res.on("data",d=>a.push(d));res.on("end",()=>resolve(Buffer.concat(a)))});r.setTimeout(timeout,()=>r.destroy(new Error("timeout")));r.on("error",reject)})}
async function health(port){for(let i=0;i<20;i++){try{const b=await fetchBuffer(`http://127.0.0.1:${port}/health`,1500); return parseJson(b.toString("utf8"))}catch{} await new Promise(r=>setTimeout(r,500))} throw new Error("Health check failed")}
function findBrowser(){const c=[process.env.ProgramFiles&&path.join(process.env.ProgramFiles,"Google/Chrome/Application/chrome.exe"),process.env["ProgramFiles(x86)"]&&path.join(process.env["ProgramFiles(x86)"],"Microsoft/Edge/Application/msedge.exe"),process.env.ProgramFiles&&path.join(process.env.ProgramFiles,"Microsoft/Edge/Application/msedge.exe")].filter(Boolean);return c.find(fs.existsSync)}
function killTree(pid){try{run("taskkill",["/PID",String(pid),"/T","/F"])}catch{}}
function updateJsonVersion(v){const p=path.join(CONFIG,"update.json"); if(!fs.existsSync(p))return; try{const j=parseJson(fs.readFileSync(p,"utf8"));j.current_app_version=v;fs.writeFileSync(p,JSON.stringify(j,null,2))}catch{}}
async function updateApp(){const p=path.join(CONFIG,"update.json");if(!fs.existsSync(p)){log("WARN","update.json yok; guncelleme atlandi.");return}const cfg=parseJson(fs.readFileSync(p,"utf8")),local=cfg.current_app_version||"0.0.0";let man;try{man=parseJson((await fetchBuffer(cfg.manifest_url,15000)).toString("utf8"))}catch(e){log("WARN",`Manifest okunamadi: ${e.message}`);return}log("INFO",`Yerel uygulama=${local}, GitHub son surum=${man.version}`);if(man.version===local)return;const tmp=path.join(RUNTIME,`update_${man.version}.zip`);fs.writeFileSync(tmp,await fetchBuffer(man.zip_url,30000));const actual=sha256(tmp);if(actual.toLowerCase()!==String(man.sha256).toLowerCase())throw new Error(`SHA256 uyusmuyor expected=${man.sha256} actual=${actual}`);const stage=path.join(RUNTIME,`stage_${Date.now()}`);fs.rmSync(stage,{recursive:true,force:true});fs.mkdirSync(stage,{recursive:true});let ex=run("tar.exe",["-xf",tmp,"-C",stage]);if(ex.status!==0)ex=run("tar",["-xf",tmp,"-C",stage]);if(ex.status!==0)throw new Error("ZIP acilamadi (tar.exe)");const test=run(process.execPath,[path.join(stage,"app","tests.js")]);if(test.status!==0)throw new Error("Guncelleme kod testi basarisiz");const backup=path.join(RUNTIME,"last_good_app");fs.rmSync(backup,{recursive:true,force:true});if(fs.existsSync(APP))fs.renameSync(APP,backup);try{fs.renameSync(path.join(stage,"app"),APP);updateJsonVersion(man.version);log("INFO",`Guncelleme tamamlandi: ${man.version}`)}catch(e){if(fs.existsSync(APP))fs.rmSync(APP,{recursive:true,force:true});if(fs.existsSync(backup))fs.renameSync(backup,APP);throw e}}
function createReport(finalState,exitCode){try{for(const f of fs.readdirSync(ROOT))if(/^RAPOR_GONDER_.*\.zip$/i.test(f))fs.rmSync(path.join(ROOT,f),{force:true});const rep=path.join(RUNTIME,`report_${session}`);fs.rmSync(rep,{recursive:true,force:true});fs.mkdirSync(path.join(rep,"REPORT"),{recursive:true});fs.mkdirSync(path.join(rep,"LOGS"),{recursive:true});fs.mkdirSync(path.join(rep,"APP"),{recursive:true});fs.mkdirSync(path.join(rep,"TESTS"),{recursive:true});fs.copyFileSync(slog,path.join(rep,"LOGS",path.basename(slog)));const hwdiag=path.join(RUNTIME,"last_homework_analysis.json");if(fs.existsSync(hwdiag))fs.copyFileSync(hwdiag,path.join(rep,"REPORT","homework_analysis.json"));const ver=fs.existsSync(path.join(APP,"VERSION"))?fs.readFileSync(path.join(APP,"VERSION"),"utf8").trim():"unknown";fs.writeFileSync(path.join(rep,"REPORT","summary.json"),JSON.stringify({session,bootstrap:"2.1.3-node",app_version:ver,final_state:finalState,exit_code:exitCode,secrets_collected:false},null,2));if(fs.existsSync(path.join(CONFIG,"update.json")))fs.copyFileSync(path.join(CONFIG,"update.json"),path.join(rep,"APP","update.json"));const tt=run(process.execPath,[path.join(APP,"tests.js")]);fs.writeFileSync(path.join(rep,"TESTS","local_code_test.txt"),(tt.stdout||"")+(tt.stderr||""));const out=path.join(ROOT,`RAPOR_GONDER_${session}.zip`);let z=run("tar.exe",["-a","-c","-f",out,"-C",rep,"."]);if(z.status!==0)z=run("tar",["-a","-c","-f",out,"-C",rep,"."]);log("INFO",`Rapor hazir: ${out}`)}catch(e){log("ERROR",`Rapor hatasi: ${e.message}`)}}
(async()=>{let server=null,code=0,state="SUCCESS";try{log("INFO","Node bootstrap v2.1.3 basladi.");if(!existsCmd(process.execPath,["--version"]))throw new Error("Node.js calismiyor");await updateApp();const t=run(process.execPath,[path.join(APP,"tests.js")]);if(t.status!==0)throw new Error("Yerel kod testi basarisiz");const port=43127;const browser=findBrowser();if(!browser)throw new Error("Chrome/Edge bulunamadi");const so=fs.openSync(path.join(LOGS,`server_${session}.log`),"a"),se=fs.openSync(path.join(LOGS,`server_error_${session}.log`),"a");server=cp.spawn(process.execPath,[path.join(APP,"server.js")],{cwd:APP,env:{...process.env,PORT:String(port),YILBAY_BROWSER_PATH:browser},detached:false,windowsHide:true,stdio:["ignore",so,se]});const h=await health(port);fs.writeFileSync(path.join(RUNTIME,"last_health.json"),JSON.stringify(h));log("INFO",`Health OK ${JSON.stringify(h)}`);const b=cp.spawn(browser,[`--app=http://127.0.0.1:${port}`,"--start-maximized",`--user-data-dir=${path.join(RUNTIME,"browser_profile")}`],{detached:false,windowsHide:false,stdio:"ignore"});await new Promise(resolve=>b.on("exit",resolve));log("INFO","Program penceresi kapatildi.")}catch(e){state="FAILED";code=1;log("ERROR",e.stack||e.message)}finally{if(server)killTree(server.pid);createReport(state,code);process.exitCode=code}})();
