import fs from 'fs';
import path from 'path';
const ROOT='/tmp/yilbay0112';
const serverPath=path.join(ROOT,'app','server.js');
let s=fs.readFileSync(serverPath,'utf8');
s=s.replaceAll('0.11.1','0.11.2');fs.writeFileSync(path.join(ROOT,'app','VERSION'),'0.11.2\n','utf8');
if(!s.includes("require('pngjs')")&&!s.includes('require("pngjs")'))s=s.replace('const http=require("http"),fs=require("fs"),path=require("path"),cp=require("child_process");','const http=require("http"),fs=require("fs"),path=require("path"),cp=require("child_process");\nconst {PNG}=require("pngjs");');
function replaceFn(src,name,nextName,repl){const a=src.indexOf('function '+name+'('),b=src.indexOf('function '+nextName+'(',a+1);if(a<0||b<0)throw new Error('function anchors '+name);return src.slice(0,a)+repl+'\n'+src.slice(b)}
const targetsFn=`function homeworkMathVerificationTargets(x={}){const out=[],seen=new Set();for(const q of [...(Array.isArray(x.wrongQuestions)?x.wrongQuestions:[]),...(Array.isArray(x.uncertainQuestions)?x.uncertainQuestions:[]),...(Array.isArray(x.blankQuestions)?x.blankQuestions:[])]){const n=normalizeHomeworkQuestionRef(q);if(n&&!seen.has(n.questionId)){seen.add(n.questionId);out.push({...n,bbox:Array.isArray(q?.bbox)?q.bbox:null})}}return out.slice(0,80)}`;
s=replaceFn(s,'homeworkMathVerificationTargets','renderHomeworkTargetPages',targetsFn);
const renderStart=s.indexOf('function renderHomeworkTargetPages('),renderEnd=s.indexOf('function applyHomeworkMathVerification(',renderStart);if(renderStart<0||renderEnd<0)throw new Error('render anchors');
const renderFns=`function renderHomeworkTargetPages(studentFile={},targets=[]){const browser=String(process.env.YILBAY_BROWSER_PATH||'').trim(),pages=[...new Set(targets.map(q=>Number(q.page)).filter(n=>Number.isInteger(n)&&n>0))].sort((x,y)=>x-y),result={mode:'high_res_page_png',requestedPages:pages,renderedPages:[],failures:[],images:[]};if(!pages.length)return result;if(!browser||!fs.existsSync(browser)){result.failures.push({page:0,error:'browser_missing'});return result}const dir=path.join(runtime,'math_verify_'+Date.now()+'_'+Math.random().toString(16).slice(2));fs.mkdirSync(dir,{recursive:true});try{const pdf=path.join(dir,'student.pdf');fs.writeFileSync(pdf,Buffer.from(String(studentFile.base64||''),'base64'));const fileUrl='file:///'+pdf.split(path.sep).join('/');for(const pageNo of pages){const out=path.join(dir,'page_'+pageNo+'.png'),profile=path.join(dir,'profile_'+pageNo),url=encodeURI(fileUrl)+'#page='+pageNo+'&zoom=page-width';const args=['--headless=new','--disable-gpu','--hide-scrollbars','--no-first-run','--disable-extensions','--force-device-scale-factor=2','--window-size=1700,2200','--virtual-time-budget=3000','--user-data-dir='+profile,'--screenshot='+out,url];let r;try{r=cp.spawnSync(browser,args,{windowsHide:true,timeout:18000,stdio:'ignore'})}catch(e){result.failures.push({page:pageNo,error:'spawn_'+String(e.message||e).slice(0,120)});continue}try{const b=fs.readFileSync(out),png=b.length>15000&&b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47;if(!png){result.failures.push({page:pageNo,error:'invalid_png'});continue}result.renderedPages.push(pageNo);result.images.push({page:pageNo,bytes:b.length,base64:b.toString('base64')})}catch{result.failures.push({page:pageNo,error:'screenshot_missing_'+String(r?.status??'')})}}}finally{fs.rmSync(dir,{recursive:true,force:true})}return result}
function normalizeHomeworkBbox(v){if(!Array.isArray(v)||v.length!==4)return null;const n=v.map(Number);if(n.some(x=>!Number.isFinite(x)))return null;let [x0,y0,x1,y1]=n.map(x=>Math.max(0,Math.min(1,x)));if(x1<=x0||y1<=y0)return null;const padX=Math.max(.025,(x1-x0)*.10),padY=Math.max(.035,(y1-y0)*.14);return [Math.max(0,x0-padX),Math.max(0,y0-padY),Math.min(1,x1+padX),Math.min(1,y1+padY)]}
function cropHomeworkTargetImages(render={},targets=[]){const byPage=new Map((render.images||[]).map(im=>[Number(im.page),im])),crops=[],failures=[];for(const t of targets){const im=byPage.get(Number(t.page));if(!im){failures.push({questionId:t.questionId,error:'page_image_missing'});continue}const box=normalizeHomeworkBbox(t.bbox);if(!box){failures.push({questionId:t.questionId,error:'bbox_missing'});continue}try{const src=PNG.sync.read(Buffer.from(im.base64,'base64')),[x0,y0,x1,y1]=box,left=Math.floor(x0*src.width),top=Math.floor(y0*src.height),right=Math.ceil(x1*src.width),bottom=Math.ceil(y1*src.height),w=Math.max(1,right-left),h=Math.max(1,bottom-top),dst=new PNG({width:w,height:h});PNG.bitblt(src,dst,left,top,w,h,0,0);const b=PNG.sync.write(dst);crops.push({questionId:t.questionId,page:t.page,sectionKey:t.sectionKey,section:t.section,printedNumber:t.printedNumber,bbox:box,width:w,height:h,bytes:b.length,base64:b.toString('base64')})}catch(e){failures.push({questionId:t.questionId,error:'crop_'+String(e.message||e).slice(0,120)})}}return {mode:'high_res_question_crop_png',crops,failures}}
`;
s=s.slice(0,renderStart)+renderFns+s.slice(renderEnd);
const h0=s.indexOf('async function handleHomework(req,res){'),h1=s.indexOf('\nfunction reportText',h0);if(h0<0||h1<0)throw new Error('handle anchors');let h=s.slice(h0,h1);
h=h.replace("const firstAi=await openaiRequest({instructions:lunaHomeworkDirectInstruction()+'\\n'+scanSchema,input:[{role:'user',content:firstContent}],reasoning:'low'});","const firstAi=await openaiRequest({instructions:lunaHomeworkDirectInstruction()+'\\nBOŞ, YANLIŞ ve BELİRSİZ olarak sınıfladığın her soru için bbox:[x0,y0,x1,y1] ver. Koordinatlar 0..1 aralığında tüm fiziksel sayfaya göre normalize edilmeli ve basılı soru metni ile öğrencinin çözüm alanının tamamını kapsamalı. Doğru sorularda bbox gerekmez.\\n'+scanSchema,input:[{role:'user',content:firstContent}],reasoning:'low'});");
h=h.replace("const firstPassMs=Date.now()-firstStarted;let parsed=normalizeHomeworkAnalysis(parseJsonText(firstAi.text));","const firstPassMs=Date.now()-firstStarted;const firstRaw=parseJsonText(firstAi.text),bboxMap=new Map();for(const q of [...(Array.isArray(firstRaw.blankQuestions)?firstRaw.blankQuestions:[]),...(Array.isArray(firstRaw.uncertainQuestions)?firstRaw.uncertainQuestions:[]),...(Array.isArray(firstRaw.items)?firstRaw.items:[])]){const k=String(q?.sectionKey||'')+'|'+Number(q?.page||0)+'|'+Number(q?.printedNumber||q?.question||0);if(Array.isArray(q?.bbox))bboxMap.set(k,q.bbox)}let parsed=normalizeHomeworkAnalysis(firstRaw);");
h=h.replace("const targets=homeworkMathVerificationTargets(parsed);let secondAi=null,secondCost=null,secondPassMs=0,render={mode:'high_res_page_png',requestedPages:[],renderedPages:[],failures:[],images:[]};","let targets=homeworkMathVerificationTargets(parsed).map(q=>({...q,bbox:bboxMap.get(String(q.sectionKey||'')+'|'+Number(q.page||0)+'|'+Number(q.printedNumber||0))||q.bbox||null}));let secondAi=null,secondCost=null,secondPassMs=0,render={mode:'high_res_page_png',requestedPages:[],renderedPages:[],failures:[],images:[]},crop={mode:'high_res_question_crop_png',crops:[],failures:[]};");
const oldIf=h.match(/if\(targets\.length\)\{const secondStarted=Date\.now\(\);render=renderHomeworkTargetPages[\s\S]*?\}else\{parsed=\{\.\.\.parsed,mathVerificationTargetCount:0,mathVerificationReviewedCount:0,mathVerificationLowConfidenceCount:0,mathVerificationComplete:true,mathVerificationUsed:false\}\}/)?.[0];if(!oldIf)throw new Error('second pass block');
const newIf=`if(targets.length){const secondStarted=Date.now();render=renderHomeworkTargetPages(studentFile,targets);crop=cropHomeworkTargetImages(render,targets);const activeTargets=targets.filter(q=>crop.crops.some(c=>c.questionId===q.questionId));if(activeTargets.length&&crop.crops.length){const targetMeta=activeTargets.map(q=>({sectionKey:q.sectionKey,section:q.section,page:q.page,printedNumber:q.printedNumber,questionId:q.questionId,bbox:q.bbox})),secondContent=[{type:'input_text',text:JSON.stringify({targets:targetMeta,manualAnswerKey:answerKey||null})},{type:'input_text',text:'İKİNCİ GEÇİŞ: Her görüntü yalnız tek hedef sorunun basılı metni ve öğrencinin çözüm alanıdır. Önce çözüm alanında gerçekten öğrenci yazısı var mı belirle. Yazı varsa blank deme. Sonra sembolleri satır satır transkribe et ve matematiği kontrol et.'}];for(const im of crop.crops){secondContent.push({type:'input_text',text:'Hedef '+im.questionId+' — sayfa '+im.page+', soru '+im.printedNumber+':' });secondContent.push({type:'input_image',image_url:'data:image/png;base64,'+im.base64,detail:'high'})}const verifySchema='Yalnız JSON: {"reviews":[{"sectionKey":"string","section":"string","page":number,"printedNumber":number,"finalStatus":"correct|wrong|blank|uncertain","hasStudentWork":boolean,"transcriptionLines":["string"],"symbolConfidence":number,"studentAnswer":"string|null","correctAnswer":"string|null","approach":"string|null","stepsSummary":["string"],"firstErrorStep":"string|null","errorCategory":"conceptual|arithmetic|attention|method|incomplete|uncertain","betterApproach":"string|null","learningObjective":"string|null","solutionConfidence":number,"note":"string|null"}]}';secondAi=await openaiRequest({instructions:homeworkMathVerificationInstruction()+'\\nBir görüntüde görünür öğrenci çözümü/işareti varsa hasStudentWork=true yap ve finalStatus=blank verme.\\n'+verifySchema,input:[{role:'user',content:secondContent}],reasoning:'low'});const secondParsed=parseJsonText(secondAi.text);parsed=applyHomeworkMathVerification(parsed,secondParsed.reviews);secondCost=appendUsage('homework_math_verify_crop',secondAi.model,secondAi.data?.usage||{}, {studentId:assignment?.studentId||null,assignmentId:assignment?.id||null,targetCount:targets.length,cropCount:crop.crops.length})}else{parsed=applyHomeworkMathVerification(parsed,[])}secondPassMs=Date.now()-secondStarted;parsed=validateLunaQuestionAccounting(parsed);parsed=deriveHomeworkReviewReasons(parsed)}else{parsed={...parsed,mathVerificationTargetCount:0,mathVerificationReviewedCount:0,mathVerificationLowConfidenceCount:0,mathVerificationComplete:true,mathVerificationUsed:false}}`;
h=h.replace(oldIf,newIf);
h=h.replace("parsed.analysisArchitecture='two_pass_luna_high_res_page_png';parsed.mathVerificationRenderMode=render.mode;parsed.mathVerificationRequestedPages=render.requestedPages;parsed.mathVerificationRenderedPages=render.renderedPages;parsed.mathVerificationRenderFailureCount=render.failures.length;","parsed.analysisArchitecture='two_pass_luna_question_crop_png';parsed.mathVerificationRenderMode=crop.mode;parsed.mathVerificationRequestedPages=render.requestedPages;parsed.mathVerificationRenderedPages=render.renderedPages;parsed.mathVerificationRenderFailureCount=render.failures.length+crop.failures.length;parsed.mathVerificationCropCount=crop.crops.length;parsed.mathVerificationCropFailureCount=crop.failures.length;");
s=s.slice(0,h0)+h+s.slice(h1);
s=s.replace("mathVerificationRenderFailureCount:Number(analysis.mathVerificationRenderFailureCount)||0,","mathVerificationRenderFailureCount:Number(analysis.mathVerificationRenderFailureCount)||0,mathVerificationCropCount:Number(analysis.mathVerificationCropCount)||0,mathVerificationCropFailureCount:Number(analysis.mathVerificationCropFailureCount)||0,");
fs.writeFileSync(serverPath,s,'utf8');console.log('v0.11.2 question crop patch applied');
