import fs from 'fs';
import path from 'path';
const ROOT='/tmp/yilbay0107';
const serverPath=path.join(ROOT,'app','server.js');
const appPath=path.join(ROOT,'app','public','app.js');
const bootPath=path.join(ROOT,'app','bootstrap','orchestrator_node.js');
let s=fs.readFileSync(serverPath,'utf8');
let a=fs.readFileSync(appPath,'utf8');
let b=fs.readFileSync(bootPath,'utf8');
s=s.replaceAll('0.10.6','0.10.7');a=a.replaceAll('0.10.6','0.10.7');
fs.writeFileSync(path.join(ROOT,'app','VERSION'),'0.10.7\n','utf8');
const oldDiag="analysisArchitecture:String(analysis.analysisArchitecture||''),wrongDetailCount:Array.isArray(analysis.items)?analysis.items.length:0,correctQuestionCount:Array.isArray(analysis.correctQuestionNumbers)?analysis.correctQuestionNumbers.length:0,blankQuestionCount:Array.isArray(analysis.blankQuestionNumbers)?analysis.blankQuestionNumbers.length:0,costTry:Number(cost?.try)||0,secretsCollected:false,contentCollected:false";
const newDiag="analysisArchitecture:String(analysis.analysisArchitecture||''),wrongDetailCount:Array.isArray(analysis.items)?analysis.items.length:0,correctQuestionCount:Array.isArray(analysis.correctQuestionNumbers)?analysis.correctQuestionNumbers.length:0,blankQuestionCount:Array.isArray(analysis.blankQuestionNumbers)?analysis.blankQuestionNumbers.length:0,uncertainQuestionCount:Array.isArray(analysis.uncertainQuestionNumbers)?analysis.uncertainQuestionNumbers.length:0,correctQuestionNumbers:Array.isArray(analysis.correctQuestionNumbers)?analysis.correctQuestionNumbers.slice(0,1000):[],wrongQuestionNumbers:Array.isArray(analysis.items)?analysis.items.map(x=>Number(x?.question)).filter(n=>Number.isInteger(n)&&n>0).slice(0,1000):[],blankQuestionNumbers:Array.isArray(analysis.blankQuestionNumbers)?analysis.blankQuestionNumbers.slice(0,1000):[],uncertainQuestionNumbers:Array.isArray(analysis.uncertainQuestionNumbers)?analysis.uncertainQuestionNumbers.slice(0,1000):[],costTry:Number(cost?.try)||0,secretsCollected:false,contentCollected:false";
if(!s.includes(oldDiag))throw new Error('homework diagnostic anchor missing');
s=s.replace(oldDiag,newDiag);
const reportAnchor='function handleHomeworkReportDownload(u,res){';
const idx=s.indexOf(reportAnchor);if(idx<0)throw new Error('report download anchor missing');
const pdfDiag="function writeHomeworkPdfDiagnostic(x={}){const safe={timestamp:new Date().toISOString(),generated:x.generated===true,reportId:String(x.reportId||'').slice(0,80),sizeBytes:Math.max(0,Number(x.sizeBytes)||0),error:String(x.error||'').slice(0,300),secretsCollected:false,contentCollected:false};fs.mkdirSync(runtime,{recursive:true});fs.writeFileSync(path.join(runtime,'last_homework_pdf.json'),JSON.stringify(safe,null,2),'utf8');return safe}\n";
s=s.slice(0,idx)+pdfDiag+s.slice(idx);
const oldHandler="async function handleHomeworkReportPdf(req,res){const body=await readJson(req,1024*1024),safe=sanitizeHomeworkReportPayload(body),out=generateHomeworkReportPdf(safe);return json(res,200,{ok:true,...out})}";
const newHandler="async function handleHomeworkReportPdf(req,res){try{const body=await readJson(req,1024*1024),safe=sanitizeHomeworkReportPayload(body),out=generateHomeworkReportPdf(safe);writeHomeworkPdfDiagnostic({generated:true,reportId:out.reportId,sizeBytes:out.size});return json(res,200,{ok:true,...out})}catch(e){writeHomeworkPdfDiagnostic({generated:false,error:e.message||'PDF karne oluşturulamadı'});return json(res,500,{ok:false,error:e.message||'PDF karne oluşturulamadı'})}}";
if(!s.includes(oldHandler))throw new Error('PDF handler anchor missing');
s=s.replace(oldHandler,newHandler);
b=b.replaceAll('2.1.3-node','2.1.4-node');
const copyAnchor="const hwdiag=path.join(RUNTIME,\"last_homework_analysis.json\");if(fs.existsSync(hwdiag))fs.copyFileSync(hwdiag,path.join(rep,\"REPORT\",\"homework_analysis.json\"));";
if(!b.includes(copyAnchor))throw new Error('bootstrap report anchor missing');
b=b.replace(copyAnchor,copyAnchor+"const pdfdiag=path.join(RUNTIME,\"last_homework_pdf.json\");if(fs.existsSync(pdfdiag))fs.copyFileSync(pdfdiag,path.join(rep,\"REPORT\",\"homework_pdf.json\"));");
fs.writeFileSync(serverPath,s,'utf8');fs.writeFileSync(appPath,a,'utf8');fs.writeFileSync(bootPath,b,'utf8');
console.log('v0.10.7 diagnostic patch applied');
