import fs from 'fs';
import path from 'path';
const ROOT='/tmp/yilbay0103';
const mp=path.join(ROOT,'cells','micro-cell-manifest.json');
const m=JSON.parse(fs.readFileSync(mp,'utf8'));
if(m.version!=='0.10.2'||m.protocol!=='micro-cell-v2-ast')throw new Error('Expected verified v0.10.2 source');
for(const e of [...m.frontend,...m.backend]){const p=path.join(ROOT,e.file);let s=fs.readFileSync(p,'utf8');s=s.replaceAll('0.10.2','0.10.3');fs.writeFileSync(p,s,'utf8')}
const byName=(arr,n)=>arr.find(x=>x.name===n);
const analyze=byName(m.frontend,'analyzeAssignment'),submit=byName(m.frontend,'submitHomeworkAnalysis'),handle=byName(m.backend,'handleHomework');
if(!analyze||!submit||!handle)throw new Error('Required cells missing');

// Frontend: source chooser + rich report UI.
let as=fs.readFileSync(path.join(ROOT,analyze.file),'utf8');
as=as.replace('<div class="field"><label>Öğrencinin tamamladığı PDF veya görsel</label><input id="homeworkFile" type="file" accept=".pdf,image/png,image/jpeg,image/webp"></div>',`<div class="field"><label>Ödev dosyası kaynağı</label><select id="homeworkSource" onchange="toggleHomeworkSource()"><option value="local">Bu bilgisayardan</option><option value="drive">Google Drive</option></select></div>\n <div id="homeworkLocalWrap" class="field"><label>Öğrencinin tamamladığı PDF veya görsel</label><input id="homeworkFile" type="file" accept=".pdf,image/png,image/jpeg,image/webp"></div>\n <div id="homeworkDriveWrap" class="field" style="display:none"><label>Drive dosya bağlantısı veya kimliği</label><input id="homeworkDriveInput" placeholder="https://drive.google.com/file/d/... veya dosya kimliği"></div>`);
as=as.replace('AI; doğru, yanlış ve boşları; görülebilen çözüm yollarını; hata türlerini ve başarı yüzdesini çıkarır. Cevap anahtarı verilirse doğruluk yükselir.','AI; doğru, yanlış ve boşları belirler. Ayrıca öğrencinin el yazısı çözüm adımlarını, kullandığı yöntemi, ilk hata adımını, kavramsal/işlemsel/dikkat hatalarını, gereksiz veya eksik adımları ve daha uygun çözüm yaklaşımını soru bazında değerlendirir.');
fs.writeFileSync(path.join(ROOT,analyze.file),as,'utf8');

const toggle=`window.toggleHomeworkSource=()=>{const src=q("homeworkSource")?.value||"local";const l=q("homeworkLocalWrap"),d=q("homeworkDriveWrap");if(l)l.style.display=src==="local"?"":"none";if(d)d.style.display=src==="drive"?"":"none"}\n`;
const driveId=`function driveFileIdFromInput(v){const s=String(v||'').trim();if(!s)return null;const m=s.match(/\/d\/([A-Za-z0-9_-]{10,})/)||s.match(/[?&]id=([A-Za-z0-9_-]{10,})/);return m?m[1]:(/^[A-Za-z0-9_-]{10,}$/.test(s)?s:null)}\n`;
const sp=path.join(ROOT,submit.file);let ss=fs.readFileSync(sp,'utf8');
ss=ss.replace(' const a=db.assignments.find(x=>x.id===id),file=q("homeworkFile")?.files?.[0];if(!a||!file)return alert("Ödev dosyasını seçin");\n if(file.size>14*1024*1024)return alert("Bu sürümde dosya en fazla 14 MB olabilir.");',` const a=db.assignments.find(x=>x.id===id),studentFileSource=q("homeworkSource")?.value||"local",file=q("homeworkFile")?.files?.[0],studentDriveFileId=driveFileIdFromInput(q("homeworkDriveInput")?.value);if(!a)return;\n if(studentFileSource==="local"&&!file)return alert("Ödev dosyasını seçin");\n if(studentFileSource==="drive"&&!studentDriveFileId)return alert("Geçerli Drive dosya bağlantısı veya kimliği girin");\n if(file&&file.size>14*1024*1024)return alert("Bu sürümde dosya en fazla 14 MB olabilir.");`);
ss=ss.replace('  const fileData=await fileToBase64(file),answerKey=q("answerKey").value.trim()||null,resourceContext=assignmentResourceContext(a);\n  const data=await apiJson("/api/ai/analyze-homework",{fileData,mimeType:file.type||"application/pdf",fileName:file.name,assignment:{id:a.id,studentId:a.studentId,course:a.course,topic:a.topic,title:a.title},answerKey,resourceContext});',`  const fileData=studentFileSource==="local"?await fileToBase64(file):null,answerKey=q("answerKey").value.trim()||null,resourceContext=assignmentResourceContext(a);\n  const data=await apiJson("/api/ai/analyze-homework",{studentFileSource,studentDriveFileId,fileData,mimeType:file?.type||"application/pdf",fileName:file?.name||"drive_odev.pdf",assignment:{id:a.id,studentId:a.studentId,course:a.course,topic:a.topic,title:a.title},answerKey,resourceContext});`);
ss=ss.replace('fileName:file.name,fileSize:file.size,mimeType:file.type||"application/pdf"', 'fileName:file?.name||"Drive ödevi",fileSize:file?.size||0,mimeType:file?.type||"application/pdf",studentFileSource');
ss=ss.replace('<div class="section"><h3>Zayıf Alanlar</h3>',`<div class="section"><h3>Çözüm Yaklaşımı ve Hatalar</h3>${(an.items||[]).map(x=>\`<div class="card" style="margin:8px 0"><div class="cell-title">Soru ${x.question||"?"} · ${x.status||"uncertain"}</div><div class="cell-sub">Yaklaşım: ${x.approach||"—"}<br>İlk hata: ${x.firstErrorStep||"—"}<br>Hata sınıfı: ${x.errorCategory||"—"}<br>Daha iyi yaklaşım: ${x.betterApproach||"—"}<br>Kazanım: ${x.learningObjective||"—"}</div></div>\`).join("")||"—"}</div>\n   <div class="section"><h3>Pedagojik Özet</h3><div class="cell-sub">${an.reasoningProfile?.summary||an.summary||"—"}</div></div>\n   <div class="section"><h3>Zayıf Alanlar</h3>`);
fs.writeFileSync(sp,ss,'utf8');

// Backend: isolate file source routing. Local mode must never call Drive.
const resolver=`async function resolveStudentHomeworkFile(body={}){const source=String(body.studentFileSource||'local');if(source==='local'){if(!body.fileData)throw new Error('Ödev dosyası gerekli');return {source:'local',base64:body.fileData,mimeType:body.mimeType||'application/pdf',fileName:body.fileName||'odev.pdf',driveUsed:false}}if(source==='drive'){if(!body.studentDriveFileId)throw new Error('Drive ödev dosyası kimliği gerekli');const f=await driveDownloadAnalysisFile(body.studentDriveFileId);return {source:'drive',base64:f.base64,mimeType:f.mimeType||'application/pdf',fileName:body.fileName||'drive_odev.pdf',driveUsed:true}}throw new Error('Geçersiz ödev dosyası kaynağı')}\n`;
const reasoning=`function homeworkReasoningInstruction(){return \`EL YAZISI ÇÖZÜM ANALİZİ PROTOKOLÜ:\nHer soruda yalnız son cevabı değil öğrencinin görülebilen el yazısı çözümünü de incele. approach alanında yöntemi özetle. stepsSummary ile görülen temel adımları sırayla yaz. firstErrorStep ilk hatalı/eksik adımı belirtir. errorCategory yalnız conceptual|arithmetic|attention|method|incomplete|none|uncertain değerlerinden biri olsun. conceptualIssue, arithmeticIssue ve attentionIssue alanlarını gerektiğinde doldur. methodQuality efficient|acceptable|inefficient|incorrect|uncertain olsun. Doğru sonuca hatalı veya tesadüfi yöntemle ulaşıldıysa bunu note içinde açıkça belirt. unnecessarySteps ve missingSteps dizilerini üret. betterApproach daha uygun yöntemi kısa ve pedagojik biçimde açıklar. learningObjective öğrencinin tekrar etmesi gereken kazanımı belirtir. solutionConfidence 0-1 arasıdır. El yazısı okunamıyorsa tahmin etme, uncertain yap. Üst düzey reasoningProfile içinde strengths, recurringErrors, conceptualGaps, proceduralGaps, attentionPatterns, recommendedActions ve summary üret.\`}\n`;
const hp=path.join(ROOT,handle.file);let hs=fs.readFileSync(hp,'utf8');
hs=hs.replace('async function handleHomework(req,res){',resolver+reasoning+'async function handleHomework(req,res){');
hs=hs.replace('  const body=await readJson(req,18*1024*1024);\n  const {fileData,mimeType="application/pdf",fileName="odev.pdf",assignment,answerKey=null,resourceContext=null}=body;\n  if(!fileData) return json(res,400,{ok:false,error:"Ödev dosyası gerekli"});',`  const body=await readJson(req,18*1024*1024);\n  const {assignment,answerKey=null,resourceContext=null,studentFileSource="local"}=body;\n  let studentFile;try{studentFile=await resolveStudentHomeworkFile(body)}catch(e){return json(res,400,{ok:false,error:e.message})}\n  const {base64:fileData,mimeType,fileName}=studentFile;`);
hs=hs.replace('  const answerKeySearch=homeworkAnswerKeySearchInstruction();', '  const answerKeySearch=homeworkAnswerKeySearchInstruction();\n  const reasoningInstruction=homeworkReasoningInstruction();');
hs=hs.replace('${answerKeySearch}\nCevap anahtarı kanıtı', '${answerKeySearch}\n${reasoningInstruction}\nCevap anahtarı kanıtı');
hs=hs.replace('"items":[{"question":number,"status":"correct|wrong|blank|uncertain","studentAnswer":"string|null","correctAnswer":"string|null","errorType":"string|null","note":"string|null"}]', '"items":[{"question":number,"status":"correct|wrong|blank|uncertain","studentAnswer":"string|null","correctAnswer":"string|null","approach":"string|null","stepsSummary":["string"],"firstErrorStep":"string|null","errorCategory":"conceptual|arithmetic|attention|method|incomplete|none|uncertain","conceptualIssue":"string|null","arithmeticIssue":"string|null","attentionIssue":"string|null","methodQuality":"efficient|acceptable|inefficient|incorrect|uncertain","unnecessarySteps":["string"],"missingSteps":["string"],"betterApproach":"string|null","learningObjective":"string|null","solutionConfidence":number,"errorType":"string|null","note":"string|null"}],"reasoningProfile":{"strengths":["string"],"recurringErrors":["string"],"conceptualGaps":["string"],"proceduralGaps":["string"],"attentionPatterns":["string"],"recommendedActions":["string"],"summary":"string"}');
// Live Drive references only in Drive-source mode. Local upload must not touch Drive at all.
hs=hs.replace('  if(resourceContext?.driveFileId){', '  if(studentFileSource===\"drive\"&&resourceContext?.driveFileId){');
hs=hs.replace('  if(resourceContext?.answerKeyDriveFileId){', '  if(studentFileSource===\"drive\"&&resourceContext?.answerKeyDriveFileId){');
hs=hs.replace('  writeHomeworkDiagnostic(parsed,cost,assignment);', '  parsed.studentFileSource=studentFileSource;parsed.studentFileDriveUsed=!!studentFile.driveUsed;\n  writeHomeworkDiagnostic(parsed,cost,assignment);');
fs.writeFileSync(hp,hs,'utf8');

// Insert independent frontend cells before submit cell content in runtime bundle by appending helpers to preceding segment source.
const submitIndex=m.frontend.findIndex(x=>x.name==='submitHomeworkAnalysis');
const prev=m.frontend[submitIndex-1];if(!prev)throw new Error('submit predecessor missing');
const pp=path.join(ROOT,prev.file);fs.writeFileSync(pp,fs.readFileSync(pp,'utf8')+toggle+driveId,'utf8');

const frontend=m.frontend.map(e=>fs.readFileSync(path.join(ROOT,e.file),'utf8')).join('');
const backend=m.backend.map(e=>fs.readFileSync(path.join(ROOT,e.file),'utf8')).join('');
fs.writeFileSync(path.join(ROOT,'app','public','app.js'),frontend,'utf8');fs.writeFileSync(path.join(ROOT,'app','server.js'),backend,'utf8');fs.writeFileSync(path.join(ROOT,'app','VERSION'),'0.10.3\n','utf8');
console.log('v0.10.3 deep homework reasoning and source routing patch applied');