async function handleHomework(req,res){
  const totalStarted=Date.now(),body=await readJson(req,18*1024*1024);
  const {assignment,answerKey=null,resourceContext=null,studentFileSource='local'}=body;
  let studentFile;try{studentFile=await resolveStudentHomeworkFile(body)}catch(e){return json(res,400,{ok:false,error:e.message})}
  if(!integrationStatus().openai.configured)return json(res,400,{ok:false,error:'Ödev analizi için OpenAI API anahtarı gerekli'});
  const expectedStudentPages=estimatePdfPageCount(studentFile.base64,studentFile.mimeType);
  const safeContext=resourceContext?{resourceId:resourceContext.resourceId||null,course:resourceContext.course||assignment?.course||'',unit:resourceContext.unit||'',topic:resourceContext.topic||assignment?.topic||'',level:resourceContext.level||'',title:resourceContext.title||assignment?.title||''}:null;
  const meta={assignment:{id:assignment?.id||null,course:assignment?.course||'',topic:assignment?.topic||'',title:assignment?.title||''},resourceContext:safeContext,manualAnswerKey:answerKey||null};
  const firstStarted=Date.now();
  const firstContent=[{type:'input_text',text:JSON.stringify(meta)},{type:'input_text',text:'BİRİNCİ GEÇİŞ: Tüm sayfaları tara; bölüm/test ve soru kimliklerini koru. Yalnız doğru/yanlış/boş/belirsiz sınıflaması yap. Yanlış çözüm ayrıntısını bu geçişte üretme.'},{type:'input_file',filename:studentFile.fileName,file_data:'data:'+studentFile.mimeType+';base64,'+studentFile.base64}];
  const scanSchema='Sadece geçerli ve KISA JSON döndür. Şema: {\"confidence\":number,\"needsTeacherReview\":boolean,\"correctQuestions\":[{\"sectionKey\":\"string\",\"section\":\"string\",\"page\":number,\"printedNumber\":number}],\"blankQuestions\":[aynı kimlik],\"uncertainQuestions\":[aynı kimlik],\"items\":[{\"sectionKey\":\"string\",\"section\":\"string\",\"page\":number,\"printedNumber\":number,\"status\":\"wrong\"}],\"reasoningProfile\":{\"strengths\":[],\"recurringErrors\":[],\"conceptualGaps\":[],\"proceduralGaps\":[],\"attentionPatterns\":[],\"recommendedActions\":[],\"summary\":\"\"},\"summary\":\"string\",\"answerKeyFound\":boolean,\"answerKeySource\":\"manual|embedded_same_page|embedded_adjacent_page|embedded_end_pages|ambiguous|none\",\"answerKeyOriginDocument\":\"manual|student_pdf|ambiguous|none\",\"answerKeyConfidence\":number,\"answerKeyEvidence\":\"string\",\"analyzedStudentPages\":[number]}';
  const firstAi=await openaiRequest({instructions:lunaHomeworkDirectInstruction()+'\nBOŞ, YANLIŞ ve BELİRSİZ olarak sınıfladığın her soru için bbox:[x0,y0,x1,y1] ver. Koordinatlar 0..1 aralığında tüm fiziksel sayfaya göre normalize edilmeli ve basılı soru metni ile öğrencinin çözüm alanının tamamını kapsamalı. Doğru sorularda bbox gerekmez.\n'+scanSchema,input:[{role:'user',content:firstContent}],reasoning:'low'});
  const firstPassMs=Date.now()-firstStarted;const firstRaw=parseJsonText(firstAi.text),bboxMap=new Map();for(const q of [...(Array.isArray(firstRaw.blankQuestions)?firstRaw.blankQuestions:[]),...(Array.isArray(firstRaw.uncertainQuestions)?firstRaw.uncertainQuestions:[]),...(Array.isArray(firstRaw.items)?firstRaw.items:[])]){const k=String(q?.sectionKey||'')+'|'+Number(q?.page||0)+'|'+Number(q?.printedNumber||q?.question||0);if(Array.isArray(q?.bbox))bboxMap.set(k,q.bbox)}let parsed=normalizeHomeworkAnalysis(firstRaw);parsed=finalizeHomeworkQuestionSets(parsed);parsed=validateLunaDirectAnswerKey(parsed,answerKey);parsed=validateHomeworkPageCoverage(parsed,expectedStudentPages,0);parsed=validateLunaQuestionAccounting(parsed);parsed=deriveHomeworkReviewReasons(parsed);
  const firstCost=appendUsage('homework_scan',firstAi.model,firstAi.data?.usage||{}, {studentId:assignment?.studentId||null,assignmentId:assignment?.id||null});
  let targets=homeworkMathVerificationTargets(parsed).map(q=>({...q,bbox:bboxMap.get(String(q.sectionKey||'')+'|'+Number(q.page||0)+'|'+Number(q.printedNumber||0))||q.bbox||null}));let secondAi=null,secondCost=null,secondPassMs=0,render={mode:'high_res_page_png',requestedPages:[],renderedPages:[],failures:[],images:[]},crop={mode:'high_res_question_crop_png',crops:[],failures:[]};
  if(targets.length){const secondStarted=Date.now();render=renderHomeworkTargetPages(studentFile,targets);crop=cropHomeworkTargetImages(render,targets);const activeTargets=targets.filter(q=>crop.crops.some(c=>c.questionId===q.questionId));if(activeTargets.length&&crop.crops.length){const targetMeta=activeTargets.map(q=>({sectionKey:q.sectionKey,section:q.section,page:q.page,printedNumber:q.printedNumber,questionId:q.questionId,bbox:q.bbox})),secondContent=[{type:'input_text',text:JSON.stringify({targets:targetMeta,manualAnswerKey:answerKey||null})},{type:'input_text',text:'İKİNCİ GEÇİŞ: Her görüntü yalnız tek hedef sorunun basılı metni ve öğrencinin çözüm alanıdır. Önce çözüm alanında gerçekten öğrenci yazısı var mı belirle. Yazı varsa blank deme. Sonra sembolleri satır satır transkribe et ve matematiği kontrol et.'}];for(const im of crop.crops){secondContent.push({type:'input_text',text:'Hedef '+im.questionId+' — sayfa '+im.page+', soru '+im.printedNumber+':' });secondContent.push({type:'input_image',image_url:'data:image/png;base64,'+im.base64,detail:'high'})}const verifySchema='Yalnız JSON: {"reviews":[{"sectionKey":"string","section":"string","page":number,"printedNumber":number,"finalStatus":"correct|wrong|blank|uncertain","hasStudentWork":boolean,"transcriptionLines":["string"],"symbolConfidence":number,"studentAnswer":"string|null","correctAnswer":"string|null","approach":"string|null","stepsSummary":["string"],"firstErrorStep":"string|null","errorCategory":"conceptual|arithmetic|attention|method|incomplete|uncertain","betterApproach":"string|null","learningObjective":"string|null","solutionConfidence":number,"note":"string|null"}]}';secondAi=await openaiRequest({instructions:homeworkMathVerificationInstruction()+'\nBir görüntüde görünür öğrenci çözümü/işareti varsa hasStudentWork=true yap ve finalStatus=blank verme.\n'+verifySchema,input:[{role:'user',content:secondContent}],reasoning:'low'});const secondParsed=parseJsonText(secondAi.text);parsed=applyHomeworkMathVerification(parsed,secondParsed.reviews);secondCost=appendUsage('homework_math_verify_crop',secondAi.model,secondAi.data?.usage||{}, {studentId:assignment?.studentId||null,assignmentId:assignment?.id||null,targetCount:targets.length,cropCount:crop.crops.length})}else{parsed=applyHomeworkMathVerification(parsed,[])}secondPassMs=Date.now()-secondStarted;parsed=validateLunaQuestionAccounting(parsed);parsed=deriveHomeworkReviewReasons(parsed)}else{parsed={...parsed,mathVerificationTargetCount:0,mathVerificationReviewedCount:0,mathVerificationLowConfidenceCount:0,mathVerificationComplete:true,mathVerificationUsed:false}}
  const totalMs=Date.now()-totalStarted,cost={try:Number(firstCost?.try||0)+Number(secondCost?.try||0),usd:Number(firstCost?.usd||0)+Number(secondCost?.usd||0),firstPass:firstCost,secondPass:secondCost};
  parsed.studentFileSource=studentFileSource;parsed.studentFileDriveUsed=!!studentFile.driveUsed;parsed.analysisArchitecture='two_pass_luna_question_crop_png';parsed.mathVerificationRenderMode=crop.mode;parsed.mathVerificationRequestedPages=render.requestedPages;parsed.mathVerificationRenderedPages=render.renderedPages;parsed.mathVerificationRenderFailureCount=render.failures.length+crop.failures.length;parsed.mathVerificationCropCount=crop.crops.length;parsed.mathVerificationCropFailureCount=crop.failures.length;parsed.firstPassMs=firstPassMs;parsed.secondPassMs=secondPassMs;parsed.totalAnalysisMs=totalMs;parsed.firstPassCostTry=Number(firstCost?.try||0);parsed.secondPassCostTry=Number(secondCost?.try||0);
  writeHomeworkDiagnostic(parsed,cost,assignment);return json(res,200,{ok:true,analysis:parsed,autoFinalize:parsed.autoFinalize,usage:{firstPass:firstAi.data?.usage||null,secondPass:secondAi?.data?.usage||null},cost});
}

