import fs from 'fs';
import path from 'path';
const ROOT='/tmp/yilbay093';
const manifestPath=path.join(ROOT,'cells','micro-cell-manifest.json');
const m=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
if(m.version!=='0.9.2'||m.protocol!=='micro-cell-v2-ast') throw new Error('Expected verified v0.9.2 micro-cell source');
for(const e of [...m.frontend,...m.backend]){const p=path.join(ROOT,e.file);let s=fs.readFileSync(p,'utf8');s=s.replaceAll('0.9.2','0.9.3');fs.writeFileSync(p,s,'utf8')}
function entry(side,name){const e=m[side].find(x=>x.name===name);if(!e)throw new Error(name+' cell missing');return e}
function writeEntry(side,name,content){fs.writeFileSync(path.join(ROOT,entry(side,name).file),content,'utf8')}
writeEntry('frontend','resources',`function resources(){\n const rows=db.resources.map(r=>\`<tr><td><div class="cell-title">\${r.title}</div><div class="cell-sub">\${r.type||"PDF"}\${r.driveSource?" · Drive":""}</div></td><td>\${r.course||"-"}</td><td>\${r.unit||"-"}</td><td>\${r.subtopic||r.topic||"-"}</td><td><span class="badge neutral">\${r.level||"-"}</span></td><td>\${Number(r.questionCount)>0?Number(r.questionCount):"-"}</td><td>\${r.answerKeyDriveFileId?'<span class="badge success">Bağlı</span>':'<span class="badge neutral">Yok</span>'}</td><td><button class="btn small" onclick="resourceEditModal(\${r.id})">Düzenle</button></td></tr>\`).join("");\n shell(\`\${pageHead("Kaynak Havuzu","PDF ödev ve çalışma kaynaklarını ders, ünite, alt konu ve zorluk düzeyine göre yönetin.",\`<button class="btn primary" onclick="resourceModal()">+ Kaynak Ekle</button>\`)}\${rows?tableWrap(\`<table><thead><tr><th>Kaynak</th><th>Ders</th><th>Ünite</th><th>Alt Konu</th><th>Seviye</th><th>Soru</th><th>Cevap Anahtarı</th><th></th></tr></thead><tbody>\${rows}</tbody></table>\`):emptyState("Kaynak bulunamadı","İlk PDF kaynağınızı ekleyin.")}\`,"resources")\n}\n`);
writeEntry('frontend','resourceModal',`window.resourceModal=()=>modal(\`<h2>Kaynak Ekle</h2><div class="formgrid"><div class="field"><label>Başlık</label><input id="rtitle"></div><div class="field"><label>Konu</label><select id="rtopic">\${topicOptions()}</select></div><div class="field"><label>Ünite</label><input id="runit"></div><div class="field"><label>Alt Konu</label><input id="rsubtopic"></div><div class="field"><label>Zorluk</label><select id="rlevel"><option>Başlangıç</option><option>Kolay</option><option>Orta</option><option>Orta-Zor</option><option>Zor</option><option>İleri</option></select></div><div class="field"><label>Soru Sayısı</label><input id="rquestioncount" type="number" min="0"></div><div class="field"><label>Drive bağlantısı / File ID</label><input id="rurl"></div><div class="field"><label>Cevap Anahtarı Drive File ID</label><input id="ranswerkey"></div></div><div class="modal-actions"><button class="btn primary" onclick="addResource()">Kaydet</button></div>\`)\n`);
writeEntry('frontend','addResource',`window.addResource=()=>{const [course,topic]=q("rtopic").value.split("|||");db.resources.push({id:Date.now(),type:"PDF",course,topic,unit:q("runit").value.trim(),subtopic:q("rsubtopic").value.trim()||topic,level:q("rlevel").value,questionCount:Math.max(0,Number(q("rquestioncount").value)||0),answerKeyDriveFileId:q("ranswerkey").value.trim(),title:q("rtitle").value||topic+" Kaynak",url:q("rurl").value});save();closeModal();resources()}\n`);
const editRel='cells/micro/frontend/043a-resourceeditmodal.cell.js';
fs.writeFileSync(path.join(ROOT,editRel),`window.resourceEditModal=(id)=>{const r=db.resources.find(x=>x.id===id);if(!r)return;modal(\`<h2>Kaynak Bilgilerini Düzenle</h2><div class="formgrid"><div class="field"><label>Başlık</label><input id="ertitle" value="\${String(r.title||'').replace(/&/g,'&amp;').replace(/\"/g,'&quot;')}"></div><div class="field"><label>Ünite</label><input id="erunit" value="\${String(r.unit||'').replace(/&/g,'&amp;').replace(/\"/g,'&quot;')}"></div><div class="field"><label>Alt Konu</label><input id="ersubtopic" value="\${String(r.subtopic||r.topic||'').replace(/&/g,'&amp;').replace(/\"/g,'&quot;')}"></div><div class="field"><label>Soru Sayısı</label><input id="erquestioncount" type="number" min="0" value="\${Number(r.questionCount)||0}"></div><div class="field"><label>Cevap Anahtarı Drive File ID</label><input id="eranswerkey" value="\${String(r.answerKeyDriveFileId||'').replace(/&/g,'&amp;').replace(/\"/g,'&quot;')}"></div></div><div class="modal-actions"><button class="btn primary" onclick="saveResourceMetadata(\${id})">Kaydet</button></div>\`)}\n`,'utf8');
const saveRel='cells/micro/frontend/043b-saveresourcemetadata.cell.js';
fs.writeFileSync(path.join(ROOT,saveRel),`window.saveResourceMetadata=(id)=>{const r=db.resources.find(x=>x.id===id);if(!r)return;r.title=q('ertitle').value.trim()||r.title;r.unit=q('erunit').value.trim();r.subtopic=q('ersubtopic').value.trim()||r.topic;r.questionCount=Math.max(0,Number(q('erquestioncount').value)||0);r.answerKeyDriveFileId=q('eranswerkey').value.trim();save();closeModal();resources()}\n`,'utf8');
writeEntry('frontend','upsertDriveResource',`function upsertDriveResource(x,newId){const matches=db.resources.map((r,i)=>({r,i})).filter(z=>z.r.driveFileId===x.id);const existing=matches[0]?.r||null;const next={type:'PDF',course:x.course,topic:x.topic,unit:x.unit||existing?.unit||'',subtopic:x.subtopic||existing?.subtopic||x.topic,level:x.level,title:x.title||x.name,questionCount:Number(x.questionCount)>0?Number(x.questionCount):(Number(existing?.questionCount)||0),answerKeyDriveFileId:x.answerKeyDriveFileId||existing?.answerKeyDriveFileId||'',url:x.webViewLink||'',driveFileId:x.id,driveModifiedTime:x.modifiedTime||null,driveSource:true};if(existing){Object.assign(existing,next);for(let i=matches.length-1;i>=1;i--)db.resources.splice(matches[i].i,1);return 'updated'}db.resources.push({id:newId,...next});return 'added'}\n`);
const parserRel='cells/micro/backend/037a-parsedriveresourcefilename.cell.js';
fs.writeFileSync(path.join(ROOT,parserRel),`function parseDriveResourceFilename(name){const base=String(name||'').replace(/\\.pdf$/i,'');const parts=base.split('__').map(x=>x.trim()).filter(Boolean);if(parts.length>=6){const [course,unit,subtopic,level,count,...titleParts]=parts;return {course,unit,subtopic,topic:subtopic,level,questionCount:Math.max(0,Number(count)||0),title:titleParts.join('__')}}if(parts.length>=4){const [course,topic,level,...titleParts]=parts;return {course,unit:'',subtopic:topic,topic,level,questionCount:0,title:titleParts.join('__')}}return {course:'',unit:'',subtopic:'',topic:'',level:'',questionCount:0,title:base}}\n`,'utf8');
writeEntry('backend','driveMetadataFromFile',`function driveMetadataFromFile(file){const ap=file.appProperties||{},parsed=parseDriveResourceFilename(file.name);let course=String(ap.yilbayCourse||parsed.course||'').trim(),unit=String(ap.yilbayUnit||parsed.unit||'').trim(),subtopic=String(ap.yilbaySubtopic||parsed.subtopic||'').trim(),topic=String(ap.yilbayTopic||parsed.topic||subtopic||'').trim(),level=String(ap.yilbayLevel||parsed.level||'').trim(),title=String(ap.yilbayTitle||parsed.title||'').trim(),questionCount=Math.max(0,Number(ap.yilbayQuestionCount||parsed.questionCount)||0),answerKeyDriveFileId=String(ap.yilbayAnswerKeyDriveFileId||'').trim();course=normalizeCourseName(course);return {course,unit,subtopic:subtopic||topic,topic:topic||subtopic,level,title:title||String(file.name||'').replace(/\\.pdf$/i,''),questionCount,answerKeyDriveFileId,matched:!!(course&&(topic||subtopic)&&level)}}\n`);
const frontend=[];for(const e of m.frontend){if(e.name==='resourceModal'){frontend.push(fs.readFileSync(path.join(ROOT,editRel),'utf8'));frontend.push(fs.readFileSync(path.join(ROOT,saveRel),'utf8'))}frontend.push(fs.readFileSync(path.join(ROOT,e.file),'utf8'))}
const backend=[];for(const e of m.backend){if(e.name==='driveMetadataFromFile')backend.push(fs.readFileSync(path.join(ROOT,parserRel),'utf8'));backend.push(fs.readFileSync(path.join(ROOT,e.file),'utf8'))}
fs.writeFileSync(path.join(ROOT,'app','public','app.js'),frontend.join(''),'utf8');fs.writeFileSync(path.join(ROOT,'app','server.js'),backend.join(''),'utf8');fs.writeFileSync(path.join(ROOT,'app','VERSION'),'0.9.3\n','utf8');console.log('v0.9.3 resource metadata patch applied');
