import fs from 'fs';
import path from 'path';
const ROOT='/tmp/yilbay0109';
const serverPath=path.join(ROOT,'app','server.js'),appPath=path.join(ROOT,'app','public','app.js');
let s=fs.readFileSync(serverPath,'utf8'),a=fs.readFileSync(appPath,'utf8');
s=s.replaceAll('0.10.8','0.10.9');a=a.replaceAll('0.10.8','0.10.9');fs.writeFileSync(path.join(ROOT,'app','VERSION'),'0.10.9\n','utf8');
function between(src,start,end,repl){const i=src.indexOf(start),j=src.indexOf(end,i+start.length);if(i<0||j<0)throw new Error('anchor '+start);return src.slice(0,i)+repl+src.slice(j)}
const finalize=`function finalizeHomeworkQuestionSets(x={}){const rawCorrect=normalizeHomeworkQuestionRefs(x.correctQuestions),rawBlank=normalizeHomeworkQuestionRefs(x.blankQuestions),rawUncertain=normalizeHomeworkQuestionRefs(x.uncertainQuestions),rawItems=[];for(const z of Array.isArray(x.items)?x.items:[]){if(String(z?.status||'wrong')!=='wrong')continue;const q=normalizeHomeworkQuestionRef(z);if(q)rawItems.push({...z,...q,question:q.printedNumber,questionLabel:q.label,status:'wrong'})}const rawWrong=normalizeHomeworkQuestionRefs(rawItems);const byId=new Map(),add=(status,list)=>{for(const q of list){const row=byId.get(q.questionId)||{ref:q,statuses:new Set()};row.statuses.add(status);byId.set(q.questionId,row)}};add('correct',rawCorrect);add('wrong',rawWrong);add('blank',rawBlank);add('uncertain',rawUncertain);const correctQuestions=[],wrongQuestions=[],blankQuestions=[],uncertainQuestions=[],conflicts=[];for(const [id,row] of byId){const statuses=[...row.statuses];if(statuses.length>1){uncertainQuestions.push(row.ref);conflicts.push({questionId:id,label:row.ref.label,statuses:statuses.sort()});continue}const st=statuses[0];if(st==='correct')correctQuestions.push(row.ref);else if(st==='wrong')wrongQuestions.push(row.ref);else if(st==='blank')blankQuestions.push(row.ref);else uncertainQuestions.push(row.ref)}const wrongIds=new Set(wrongQuestions.map(q=>q.questionId)),items=rawItems.filter(z=>wrongIds.has(z.questionId));const correct=correctQuestions.length,wrong=wrongQuestions.length,blank=blankQuestions.length,uncertain=uncertainQuestions.length,total=byId.size,classified=correct+wrong+blank+uncertain,statusConflictCount=conflicts.length,accountingOk=total>0&&classified===total,statusOk=statusConflictCount===0,score=total?Math.round(1000*correct/total)/10:0;return {...x,correctQuestions,wrongQuestions,blankQuestions,uncertainQuestions,items,correct,wrong,blank,uncertain,totalQuestions:total,classifiedQuestions:classified,scorePercent:score,questionIdentityDuplicateCount:0,questionStatusConflictCount:statusConflictCount,questionStatusConflicts:conflicts,questionStatusVerified:statusOk,questionAccountingVerified:accountingOk,correctQuestionNumbers:correctQuestions.map(q=>q.label),wrongQuestionNumbers:wrongQuestions.map(q=>q.label),blankQuestionNumbers:blankQuestions.map(q=>q.label),uncertainQuestionNumbers:uncertainQuestions.map(q=>q.label),needsTeacherReview:!!x.needsTeacherReview||!accountingOk||!statusOk,autoFinalize:!!x.autoFinalize&&accountingOk&&statusOk}}\n`;
s=between(s,'function finalizeHomeworkQuestionSets(x={}){','async function handleHomework(req,res){',finalize);
const derive=`function deriveHomeworkReviewReasons(x={}){const r=[];if(Number(x.confidence||0)<0.65)r.push('low_confidence');if(Number(x.totalQuestions||0)<=0)r.push('no_questions');if(x.questionCountMismatch)r.push('question_count_mismatch');if(x.questionAccountingVerified===false)r.push('question_accounting_mismatch');if(Number(x.questionStatusConflictCount||0)>0)r.push('question_status_conflict');if(x.pdfCoverageVerified===false)r.push('page_coverage_incomplete');if(String(x.answerKeySource||'')==='ambiguous')r.push('answer_key_ambiguous');if(x.answerKeyFound===false)r.push('answer_key_missing');if(x.answerKeyFound===true&&Number(x.answerKeyConfidence||0)<0.75)r.push('answer_key_low_confidence');if(!!x.needsTeacherReview&&!r.length)r.push('model_requested_review');return {...x,reviewReasons:[...new Set(r)],needsTeacherReview:!!x.needsTeacherReview||r.length>0,autoFinalize:!!x.autoFinalize&&r.length===0}}\n`;
s=between(s,'function deriveHomeworkReviewReasons(x={}){','function homeworkAnswerKeySearchInstruction',derive);
const diag=`function writeHomeworkDiagnostic(analysis={},cost=null,assignment=null){const safe={timestamp:new Date().toISOString(),assignmentId:assignment?.id??null,expectedStudentPages:Number(analysis.expectedStudentPages)||0,analyzedStudentPages:Array.isArray(analysis.analyzedStudentPages)?analysis.analyzedStudentPages.slice(0,500):[],missingStudentPages:Array.isArray(analysis.missingStudentPages)?analysis.missingStudentPages.slice(0,500):[],pdfCoverageVerified:!!analysis.pdfCoverageVerified,answerKeyFound:!!analysis.answerKeyFound,answerKeySource:String(analysis.answerKeySource||'none'),answerKeyConfidence:Number(analysis.answerKeyConfidence)||0,confidence:Number(analysis.confidence)||0,needsTeacherReview:!!analysis.needsTeacherReview,autoFinalize:!!analysis.autoFinalize,totalQuestions:Number(analysis.totalQuestions)||0,correct:Number(analysis.correct)||0,wrong:Number(analysis.wrong)||0,blank:Number(analysis.blank)||0,uncertain:Number(analysis.uncertain)||0,scorePercent:Number(analysis.scorePercent)||0,classifiedQuestions:Number(analysis.classifiedQuestions)||0,questionAccountingVerified:!!analysis.questionAccountingVerified,questionIdentityDuplicateCount:Number(analysis.questionIdentityDuplicateCount)||0,questionStatusConflictCount:Number(analysis.questionStatusConflictCount)||0,questionStatusVerified:analysis.questionStatusVerified!==false,questionStatusConflicts:Array.isArray(analysis.questionStatusConflicts)?analysis.questionStatusConflicts.slice(0,100).map(x=>({questionId:String(x.questionId||'').slice(0,180),label:String(x.label||'').slice(0,220),statuses:Array.isArray(x.statuses)?x.statuses.slice(0,8):[]})):[],reviewReasons:Array.isArray(analysis.reviewReasons)?analysis.reviewReasons.slice(0,20):[],analysisArchitecture:String(analysis.analysisArchitecture||''),correctQuestionNumbers:Array.isArray(analysis.correctQuestionNumbers)?analysis.correctQuestionNumbers.slice(0,1000):[],wrongQuestionNumbers:Array.isArray(analysis.wrongQuestionNumbers)?analysis.wrongQuestionNumbers.slice(0,1000):[],blankQuestionNumbers:Array.isArray(analysis.blankQuestionNumbers)?analysis.blankQuestionNumbers.slice(0,1000):[],uncertainQuestionNumbers:Array.isArray(analysis.uncertainQuestionNumbers)?analysis.uncertainQuestionNumbers.slice(0,1000):[],costTry:Number(cost?.try)||0,secretsCollected:false,contentCollected:false};fs.mkdirSync(runtime,{recursive:true});fs.writeFileSync(path.join(runtime,'last_homework_analysis.json'),JSON.stringify(safe,null,2),'utf8');return safe}\n`;
s=between(s,'function writeHomeworkDiagnostic(analysis={},cost=null,assignment=null){','function validateHomeworkQuestionAccounting',diag);
s=s.replaceAll('direct_luna_wrong_only_composite_question_id','direct_luna_wrong_only_composite_question_id_status_reconciled');
fs.writeFileSync(serverPath,s,'utf8');fs.writeFileSync(appPath,a,'utf8');
console.log('v0.10.9 status reconciliation patch applied');
